tock/hours/admin.py, tock/hours/models.py, tock/tock/templates/hours/timecard_form.html
This fixes a bug in the template associated with a new record. The div class name changed because the model name changed. 
I also added related_name fields in the models, because it helped me test.
=> fixed the save() bug

tock/hours/models.py, tock/tock/static/sass/_entries.scss
This removes related fields from models, as they broke `save()`
=> Removes related

README.md
I don't have much experience with vagrant, so I didn't know I needed to install cask separately. Added that step to the instructions in case anyone else has that problem!
=> adding cask install step to install instructions

Procfile, tock/employees/admin.py, tock/employees/management/commands/convert_users.py, tock/employees/migrations/0004_employee.py, tock/employees/models.py, tock/tock/settings/base.py
This creates a duplicate `employee` model which will eventually replace `User`. This middle step duplicates Users in to employees so that Users may be deprecated at a future time.
=> Created employee model

README.md
The base URL should be `/`, not `/tock`.
=> Remove /tock from test URLs

requirements.txt, tock/api/admin.py, tock/api/models.py, tock/api/tests.py, tock/api/urls.py, tock/api/views.py, tock/tock/settings/base.py, tock/tock/urls.py
This PR adds two API endpoints, each in JSON and CSV formats:
* `/api/projects.(json|csv)` lists the projects and their billable flag
* `/api/users.(json|csv)` lists the users by email, first and last name
I'm using [Django REST Framework](http://www.django-rest-framework.org/) because I'm lazy.
I also tweaked the whitespace in `tock/tock/urls.py`. FWIW, [flake8](https://flake8.readthedocs.org/) reports a ton of other whitespace-related warnings throughout the project, though.
No tests yet. :cry:
=> Simple API

tock/api/urls.py, tock/api/views.py
The timecards endpoint accessible at `/api/timecards.(json|csv)` accepts the following query string parameters to filter the response:
* `user`: either a username, e.g. `shawn.allen`, or a user's numeric ID
* `project`: either a project's name, e.g. `General`, or numeric ID
This endpoint returns all of the fields that should be necessary to visualize person- or project-specific reports:
- `user`: the user's username, e.g. `shawn.allen` (user IDs and full names can be cross-referenced from `/api/users.json`)
- `project`: the project name (project ID can be cross-referenced from `/api/project.json`)
- `start_date`: the reporting period start date in `YYYY-MM-DD` form
- `end_date`: the reporting period end date `YYYY-MM-DD` form
- `hours_spent`: a decimal number (encoded as a string in JSON) …
=> Add time cards API endpoint

tock/api/views.py
This PR orders the timecards API endpoint results by reporting date ascending and introduces a `date` query string parameter that filters results by whether the provided date string (in `YYYY-MM-DD` form) falls within their reporting date range.
@seanherron we could probably speed these queries up significantly with some indexes. Let me know if you want to huddle today and figure out which ones make sense so we can coordinate the order in which filters are applied to take advantage of them.
=> order timecards by date, add "date" parameter

.travis.yml, tock/hours/forms.py, tock/hours/tests/test_forms.py, tock/hours/tests/test_views.py, tock/tock/settings/test.py
This is a first stab at getting the tests running on Travis. Some notes:
1. The CSV test referred to the wrong project in the expected output. I've switched it from Peace Corps to openFEC, as the latter is the first object inserted in the setup.
1. The test settings (`tock.settings.test`) included some redundant settings that were causing Django to throw ImproperlyConfigured exceptions. Since this file imports all of the `tock.settings.base` settings, removing the redundant `INSTALLED_APPS` and other settings appeared to do the trick.
1. There are two tests for form validity that fail in the test suite, but not in the Django shell. I have no idea how to debug these, so I've disabled them now (with the `x` prefix), and could use some help from somebody with Django forms experience to …
=> Fix tests on Travis

tock/api/renderers.py, tock/api/tests.py, tock/api/urls.py, tock/api/views.py, tock/hours/fixtures/timecards.json
This PR introduces a new API endpoint, `/api/timecards_bulk.csv`, that streams the data as CSV, and should resolve #163. I basically followed [these instructions](https://docs.djangoproject.com/en/1.8/howto/outputting-csv/#streaming-large-csv-files), and wrapped up the streaming logic in a rendering function that we can use later on.
I didn't go as far as to create a [DRF renderer](http://www.django-rest-framework.org/api-guide/renderers/) class because I couldn't figure out how to get access to the view's serializer from within the renderer's `render()` method, but this would be a good thing to do in the future if we wanted any of the other CSV views to stream. The downside of this approach is that you can't calculate the `Content-Length` HTTP header, which means that browsers can't …
=> Stream CSV in bulk

tock/api/views.py
Eagerly load timecard related rows.
Currently, hitting the timecard views executes 5n+1 queries: one query
to load the relevant timecards, and five additional queries to load
related rows (projects, reporting periods, etc.) for each matching
timecard. This may be related to the slowness reported in #179. This
patch uses the `select_related` method to tell Django that related
objects should be loaded in the initial query via joins.
=> Eager load timecards

requirements.txt, tock/hours/forms.py
This PR should fix #173. The [Django 1.8 docs](https://docs.djangoproject.com/en/1.8/ref/forms/fields/#choicefield) for `django.forms.ChoiceField` claim that:
> If the [choices] argument is a callable, it is evaluated each time the field’s form is initialized.
So I've updated the `TimecardObjectForm` to look like this, and ditched the `ProjectChoiceField` class altogether:
```python
class TimecardObjectForm(forms.ModelForm):
project = forms.ChoiceField(widget=SelectWithData(), choices=projects_as_choices)
class Meta:
model = TimecardObject
fields = ['project', 'hours_spent']
```
This works for me. I've tested it:
1. by adding and removing projects while the app is running, then checking the timecard entry form to see if the list gets updated; and
1. by running the tests, naturally
and in …
=> [WIP] Use Django 1.8, fix #173

requirements-dev.txt, tock/hours/tests/test_integration.py
Add integration tests checking that the options in the project selector
are populated correctly. The `test_project_select_dynamic` test should
succeed after merging #175 but fail without the patch.
=> Add regression tests for #175.

requirements-dev.txt, tock/manage.py, tock/tock/settings/test.py
Django 1.7+ imports models before starting the testing process, so
models appear to never be tested. This patch uses a workaround described
in https://github.com/django-nose/django-nose/issues/180.
[Resolves #198]
=> Start coverage before tests.

tock/tock/templates/projects/project_detail.html
In my zeal to replace hard-coded URLs with `reverse` calls, I didn't
notice that the URL in the `utilization-chart` was actually a template.
rendered in the JS. This patch restores the previous, correct logic.
:confounded:
=> Restore correct URL template in project detail chart.

tock/hours/tests/test_views.py, tock/projects/templatetags/project_tags.py, tock/projects/tests.py, tock/projects/views.py, tock/tock/static/css/style.css, tock/tock/templates/projects/project_detail.html
It looks kind of like this:
Just imagine it with more users and reporting periods. @batemapf is this what you had in mind?
Todo:
=> Add data table of hours spent on project detail page.

tock/employees/forms.py, tock/employees/tests/test_forms.py, tock/employees/tests/test_views.py, tock/employees/views.py
Changing emails causes historical data to be disassociated from the user account. The option to change your email should not be readily available. 
[Resolves #195]
=> Removing email field from employee form

.travis.yml, tock/hours/tests/test_integration.py, tock/hours/tests/test_models.py, tock/hours/tests/test_views.py, tock/hours/views.py, tock/projects/tests.py, tock/tock/settings/dev.py, tock/tock/settings/test.py
Helpful for testing functionality outside the Django ORM, such as #208. It's also generally good practice to make testing and production environments as similar as possible.
=> Run tests against postgres.

tock/hours/tests/test_views.py, tock/tock/remote_user_auth.py, tock/tock/settings/base.py, tock/tock/tests/test_remote_user_auth.py
[Resolves #212]
Note: I put the check to ensure `UserData` in a middleware rather than the authentication backend, since it's possible (although unlikely) that a user could authenticate, somehow have their `UserData` lost, and return to Tock before their session expires. If this is too much of an edge case to worry about, we can put the check in the authentication backend.
=> Ensure that authenticated users have `UserData` records.

tock/api/tests.py, tock/api/views.py
=> Add agency name to timecards API endpoints.

deploy.sh
Since all CF requests are now redirected to HTTPS, we need to use a URL
that handles SSL. This patch maps the Tock app to tock-app.18f.gov; the
"-app" suffix is used to distinguish the route used by nginx
(tock.18f.gov) from the route used by the app.
Ping @ramirezg. We'll also need to update the staging app to live at tock-app-staging.18f.gov. See https://github.com/18F/hub/pull/358 for full configuration.
=> Map application to 18f.gov.

tock/hours/admin.py
This should allow admins to modify people's timecards without being forced to enter 40 hours for time periods shorter than 40 hours.
=> Connecting timecard working hours to admin formset

tock/projects/migrations/0002_auto_20151020_2043.py, tock/projects/models.py
add flat rate option to accounting codes.
per alan d:
1. do migrations need to run for this to take effect?
2. how can we get this field to show up in the admin panel, in the 'modify accounting code' box?
=> flat-rate-option

tock/api/tests.py, tock/api/urls.py, tock/api/views.py
One of the features that I'm hoping to eventually use is the ability
to connect Tock data with other data. Given that Tock stores some
descriptive metadata, I wanted to be able to access that data at the project
level. In other words, this PR would expose the following endpoint:
`/api/projects/:number.json`
=> Added project detail in API

tock/hours/migrations/0011_auto_20151203_1532.py, tock/hours/models.py, tock/hours/tests/test_models.py
in response to #262.  this allows an administrator to create reporting periods that are longer than 40 hours.  the only use case for this at present is, via admin privileges, modifying prior reporting periods to increase the hours ceiling and then modifying applicable time cards to include extra hours.  after modifications to individual timecards are made, the ceiling should be lowered back to 40 hours.
@geramirez mind taking a look?
cc @HuixianXu
=> Allow more than 40

README.md
This changeset addresses a missing step in the README when setting up Tock locally.  The fixture data for a user and for the projects needs to be loaded in order to access the admin site and see any project information.
=> Closes #236:  Update README with missing setup step

README.md
This changeset addresses a missing command in Getting Started instructions.  Special thanks to @jgcobb3 for the initial PR that originally fixed this!
=> Fix README.md instructions

tock/tock/templates/projects/project_list.html
adds a description to the /projects/ page, along side the name and ID of the project  cc @lanebecker
=> add description to project list

tock/api/tests.py, tock/api/views.py, tock/hours/factories.py, tock/hours/fixtures/timecards.json, tock/hours/forms.py, tock/hours/migrations/0014_timecard_submitted.py, tock/hours/models.py, tock/hours/templatetags/has_submitted_timesheet.py, tock/hours/tests/test_forms.py, tock/hours/tests/test_templatetags.py, tock/hours/tests/test_views.py, tock/hours/views.py, tock/projects/tests.py, tock/projects/views.py, tock/tock/templates/hours/timecard_form.html
This PR addresses [issue #288](https://github.com/18F/tock/issues/288). This code adds functionality to save hours throughout the week (without submitting).
A summary of the additions & changes:
This is a boolean field and defaulted to `False`. All existing timecards where `time_spent__isnull=False` are backfilled to `submitted=True` in the migration script (see `hours/migrations/0014_timecard_submitted.py`)
On the timesheet form page, there is now a "Save" button alongside the "Submit" button. 
If a user clicks "Save", the `timecard` and `timecard_objects` are added / updated in the database but the `submitted` field on the `timecard` object remains / is set to `False`. After a successful "Save", the user remains on the same page (vs. after a "Submit" which redirects the user to the …
=> Save timecard functionality (micro-purchase auction)

data-reconciliation.md, tock/api/views.py
Include the client name (accounting code and agency) with each project
when retrieving a project list using the Tock API to allow
reconciliation with Float.  See https://micropurchase.18f.gov/auctions/11
*Since the data reconciliation tool is a new application written in a different language than Tock, I put it in a [separate repo](https://github.com/cwarden/onena).  If you would prefer that I include the source within the Tock repo, or pull it in as submodule, let me know.*
=> Include Client Name in Project API Results

tock/hours/forms.py, tock/hours/tests/test_forms.py
This PR allows you to save / submit entries with 0 hours. If the hours input is left blank, you will still get the usual validation error ("the number of hours cannot be blank").
This addresses https://github.com/18F/tock/issues/339 and https://github.com/18F/tock/issues/338
=> allow for saving/submitting 0 hour entries

tock/tock/templates/hours/timecard_form.html
This PR addresses feedback by Jay Huie in Slack: "1) I think there’s a small “tock bug” - where I had one item (the last in the list) to be deleted then did “add new item” and it seemed to inherit that checkbox status."
=> clear checkbox when new line item added to page

tock/employees/admin.py, tock/employees/migrations/0007_auto_20160428_0105.py, tock/employees/models.py, tock/employees/tests/test_models.py
** replaces #348 which included unnecessary squashing of migration files **
- add employee unit field to employee model
- add choices for employee unit field
- update tests for employee model
purpose of this PR is to append more detailed employee information to tock data for: (1) business analytics; (2) billing information; and (3) end reliance on lower quality spreadsheet based roster information for the prior to items.
=> add org data to employee model

tock/hours/forms.py, tock/hours/tests/test_forms.py, tock/hours/tests/test_integration.py, tock/hours/tests/test_views.py
This fixes #353. As specified in that issue, the project labels are now prefixed with their project ID, followed by a dash:
In the above screenshot, typing `99` into the text field would cause **99 - 38r3aG Project** to be chosen. Alternatively, `38r3aG` could also be typed, and the widget would still work as it previously had (i.e., there's no regressions in the UI).
**Note:** I'm assuming here that all users have JS enabled. If they don't, and if the Chosen widget actually appears as a standard `<select>`, then some user habituation could be broken.
=> Allow autocomplete by project number.

tock/tock/settings/dev.py
This is actually a PR for #370 and makes `manage.py test` work without needing to explicitly pass-in a different settings configuration.
=> Don't load debug toolbar during unit tests.

tock/tock/settings/base.py
I *think* this fixes #371.  I haven't actually tried it out though, as I've just used GitHub's in-browser text editor to make the change.
=> Use escape sequences for unicode JSON chars in API output

.cfignore, docker-compose.yml, requirements.txt, tock/manage.py, tock/tock/settings/base.py, tock/tock/settings/dev.py, tock/tock/settings/production.py, tock/tock/settings/test.py, tock/tock/urls.py, tock/tock/wsgi.py
This changeset improves the integration of `django-debug-toolbar` with the recent support added for running Tock in a Docker container.  It also addresses an underlying issue that was present where the incorrect settings file was being used for running the `manage.py collectstatic` command and when running the app in staging or production.
The following list is a brief summary of all of the changes I made:
* Remove reference to Vagrant files and add Docker files to `.cfignore`.
* Add the `DJANGO_SETTINGS_MODULE` environment variable to `docker-compose.yml`.
* Always reference the `EXTERNAL_PORT` environment variable in `docker-compose.yml`.
* Remove `django-debug-toolbar` from `requirements.txt`.
* Default to running with `tock.settings.production` in cases where `DJANGO_SETTINGS_MODULE` …
=> Improve Django Debug Toolbar integration with Docker

tock/hours/forms.py, tock/hours/models.py, tock/hours/tests/test_integration.py, tock/hours/views.py, tock/tock/templates/hours/timecard_form.html
This fixes #380.
The regression was caused by #374, which overwrote the id-prefixed choices introduced by #360. This PR refactors some of #374 while fixing the regression.
(FYI, #374 caused another regression which prompted #378; this PR also obviates the need for that fix, due to the way it refactors and throws out duplicate code.)
=> Fix autocomplete by id.

tock/employees/migrations/0008_userdata_is_billable.py, tock/employees/models.py
- add "is_billable" to employee model to indicate whether the employee is primarily "billable" (as opposed to primarily admin / support / mgmt / non-billable)
- other minor text tweaks to employee model
=> add billable indicator to employee model

tock/api/tests.py, tock/api/urls.py, tock/api/views.py
adds a more svelte option for pull bulk tock data. ran into issues pulling the live data into google sheets off the bulk_timecards.csv endpoint. reduced the number of fields to make the load more economical. if @toolness or @ccostino have a minute or two to take a look, would much appreciate!
test coverage added, as well.
=> adds a slimmer bulk timecard endpoint

requirements.txt
Two CVE's [pop up](https://gemnasium.com/github.com/18F/tock/alerts) in Gemnasium for this version of Django, so let's bump up the
patch version (should be 100% compatible). CVEs:
* CVE-2016-2512 - MALICIOUS REDIRECT AND POSSIBLE XSS ATTACK VIA USER-SUPPLIED
REDIRECT URLS: Unsure if Tock uses redirects anywhere. Best to update to be
safe.
* CVE-2016-2513 - USER ENUMERATION THROUGH TIMING DIFFERENCE ON PASSWORD
HASHER WORK FACTOR UPGRADE: Should be a non-issue given that Tock doesn't
have local users
=> Bump Django Version

tock/api/urls.py, tock/api/views.py
accessible at /api/user_data.csv or /api/user_data.json. includes `id`, `start_date`, `end_date`, `current_employee`, `is_18f_employee`, `is_billable`, and `unit` fields
=> add user_data.csv | json endpoint

tock/tock/templates/hours/timecard_form.html
- add `search_within: true` to chosen() instantiations
- simplify calls to chosen() instantiation and event hookups
Noticed today that I was unable to just type "holiday" to find the "Administrative/Holiday Leave" project in tock. Enabling the `search_within` option in chosen selects enables searching to work within full strings instead of on space-delimited tokens.
=> match search text within dropdown options text

tock/api/views.py
repurposes the `user_data.` endpoint with the following tidy fields:
- user (string; firstname.lastname)
- current emp (t/f)
- 18f emp (t/f)
- billable employee (t/f)
- current unit (string)
=> make use of unit designation and other updates

staging-manifest.yml
ensures that the tock-staging app automatically binds to staging DB
=> add service info for staging instance

tock/tock/templates/hours/reports_list.html
Change language from "less fields" to "fewer fields".
Currently, the reports interface at https://tock.18f.gov/reports/ says "Complete timecard data with less fields".
Grammatically, this should be "Complete timecard data with fewer fields".
=> Less --> Fewer

tock/api/tests.py, tock/api/urls.py, tock/api/views.py, tock/hours/tests/test_views.py, tock/hours/urls/reports.py, tock/hours/views.py, tock/tock/templates/base.html, tock/tock/templates/hours/reports_list.html, tock/tock/templates/projects/project_detail.html, tock/tock/templates/projects/project_list.html
This change is complementary to #465 and  moves CSV reports (views, serializers, tests, and URL confs) to the /reports/ route which is behind the cloud.gov UAA authentication system. Users who consume these reports can do so after authenticating into Tock as usual.
Users getting JSON data can hit the /api/ route with a token.
Tip of the hat to @annalee for encouraging me to do this the _right_ way :-).
=> CSV download issue

staging-deploy.sh
This change updates script to new DB service (as opposed to a hardcoded DB address and key) and creates a nearly identical `staging-deploy.sh` script for zero downtime staging deploys. The staging script **must** be run in the cloud.gov staging space to avoid conflicts with the production app.
=> update b/g deployment scripts for new cloud.gov env

tock/employees/tests/test_models.py, tock/employees/tests/test_views.py, tock/employees/urls.py, tock/employees/views.py, tock/tock/templates/employees/user_detail.html, tock/tock/templates/employees/user_list.html
To address #218 and #486. 
Earlier resolution of #218 failed due to the retention of view-level permission (requiring either the requesting user be a superuser or requesting their own information). This PR addresses this issue as follows:
1. Creates a new employee detail view from the generic DetailView class that is accessible to all authenticated users;
2. Delivers this view via a new template, user_detail.html, which contains the same information from user_form.html (via UserFormView), but in static / non-editable form. [1]
3. The pre-existing UserFormView retains its permission requirement (superuser or self).
4. Testing added for new view.
5. Added new URL conf for user_detail.html and related view.
6. Updated logic on user_list.html to display one set of URLs …
=> Allow access to user detail

tock/api/views.py
all for limiting timecard reports to just those projects that are billable.
=> add billable param

tock/tock/templates/projects/project_list.html
Creates two tables on the `/projects/` page (projects_list.html template + ProjectListView view): one for active and one for inactive.
cc @ric7694, who requested.
=> Address #305 - Active vs. Inactive Projects

tock/tock/static/sass/_checkbox.scss, tock/tock/static/sass/_entries.scss, tock/tock/static/sass/core.scss
Reverts all checkboxes to use browser defaults bc of issues with USWDS checkboxes. Previously, browser default checkbox was set just on the timesheet page.
Fixes #556.
=> Revert all custom checkboxes to browser defaults

tock/tock/templates/projects/project_detail.html
Addresses #558 by displaying the Project__profit_loss_account__accounting_string value if available. If not, states that the value is not available.
=> addresses #558

tock/hours/forms.py
User could not save a timecard that contained a notes-required entry. This changeset addresses this by:
1. Only applying notes-required validation to cases where the user is attempting to submit the form, as opposed to all postings of the form;
2. Checking to see if there are any TimecardObject errors upon submission (non-save) and, if so, notifying the user that there is an error that needs to be corrected.
Successful save with no notes:
Error message when a TimecardObject submission has an issue:
=> notes validation + meaningful error message

tock/hours/forms.py, tock/hours/tests/test_forms.py
Addresses #552 by marking TimecardObject's to be DELETE'ed if they have a zero value for hours_spent. Upon merge and deployment, this will eliminate the existence of all future timecards having entries with 0 hours spent.  cc @HuixianXu and @MKathrynC who will also probably be happy to eliminate this issue.
Here is a screenshot of the problem:
After merge and deploy of this change, I also recommend we clear out all existing TimecardObjects with zero hours spent from the production database.
=> on submit, removes any TimecardObjects that have zero hours

tock/hours/forms.py
This PR patches #564 to handle situations where a submitted form within the TimecardInlineFormset is completely empty (i.e. no project, no hours_spent) and a KeyError is thrown.
=> Patch #564 to handle errors correctly

tock/tock/templates/hours/reports_list.html
Updated the page header to include the word "Tock" to be consistent with the other page names, Tock Projects and Tock Users.
Added H4 tags around the Fiscal Year text to help with visual separation and header semantics.
=> Update report page title and fiscal year headers

tock/tock/static/sass/base/_tables.scss, tock/tock/templates/utilization/group_utilization.html
Adds add'l text to the table header and adds title text to the link to describe you're looking at `Percent billable (billable hours / total hours)`. Cleans up some line breaks and removes anchor link from headers.
*Note: this is fake data for demonstration purposes.
=> Adds add'l text to table header and title text to link

tock/tock/static/sass/base/_tables.scss, tock/tock/templates/utilization/group_utilization.html, tock/utilization/tests/test_views.py, tock/utilization/utils.py, tock/utilization/views.py
First PR in a series designed to address #561 (Team Reporting Improvements). This PR updates the utilization page and corresponding GroupUtilization view by:
- adding hourly numerator and denominator information; and
- generating a link to the latest timecard for each user.
This enhancement serves as the "starting point" described by a [user](https://github.com/18F/tock/issues/561#issuecomment-261322088).
For those with staff-level access to our staging site, the proposed enhancements are viewable [here](tock.app.cloud.gov/utilization/).
=> add hours to utilization view and template, link to latest timecard

tock/hours/tests/test_views.py, tock/hours/views.py
Addresses issues raised in Slack on 11/18 re: missing names in the reports/[YYYY-MM-DD].csv file. The CSV writer relied on email address data for the "User" column of the CSV. If the user did not have an email address in the app, a blank was written in its place. This created the appearance of missing records in the output CSV.
This changes switches out email address for username, which is more reliable because all users have a username.
cc @GailSwanson @acolter
=> Fix Reporting Period CSV Report

tock/employees/admin.py, tock/employees/tests/test_admin.py
When loading in accounting code info into the production instance, I noticed an issue with the logic from #562 (Extend Profit/Loss Accounting Info): the logic unnecessarily restricts the association of accounting codes with employees based on the start date of the user and the start date of the accounting code. For instance, if I started on 12/01/2014, only accounting codes with start dates on or before that date could be associated with my UserData object. This doesn't make sense because generally accounting codes are refreshed / recreated every fiscal year.
This change backs out the overly-restrictive logic and updates tests to comply. _Note_ that this change does not impact the model-level logic for the application of revenue and expense codes to TimecardObjects: these still check to …
=> Tune Up Accounting Code Logic

tock/tock/templates/hours/reports_list.html
This change to the reports template makes use of the `?after=` parameter available via Tock's RESTful framework to give the user the option to download a CSV containing either all the data or just a single fiscal year (in this case, FY17).
Screenshot of changes:
----
=> provide user with more reporting options

tock/hours/tests/test_views.py, tock/hours/views.py, tock/tock/templates/hours/reporting_period_user_detail.html
Adds a new table to the user timecard detail page that summarizes billable hours, all hours, and billable percentage for a user in a specific reporting period. Feature requested in #551.
This change also addresses an existing n+1 query issue by prefetching project and accounting code information along with timecard info for eventual use in the template.
Screenshot of changes:
----
=> User summary row

.travis.yml
This PR adds a default timezone to .travis.yml
This prevents datetime drift related errors when running CI.
See https://github.com/18F/tock/pull/583#issuecomment-263477596
for an example of tests that can fail due to that drift.
=> Add a default timezone to .travis.yml

tock/hours/tests/test_views.py, tock/tock/static/sass/base/_tables.scss, tock/tock/templates/employees/user_list.html, tock/tock/templates/hours/reporting_period_detail.html, tock/tock/templates/hours/reporting_period_user_detail.html, tock/tock/templates/utilization/group_utilization.html
- Adds `<thead>`, `<tfoot>`, and a `<tbody>` elements to properly mark up the table. 
- Fixes markup indentation.
TODO:
=> Add appropriate elements to table markup

tock/hours/tests/test_views.py, tock/hours/views.py, tock/tock/templates/hours/dashboard.html
Rolls back the ability to "zoom in" on specific units in the Operations Dashboard, which will require a better understanding of how @joshuabailes and the business calculates such things. Also updates report so that only 18F "units" are included (excludes PIF and AcqStack) in the org-level report.
Screenshot:
=> Patch Ops Report

tock/hours/tests/test_views.py, tock/hours/views.py
Filters out projects that have Acquisition Services profit / loss information from the operations report, per @joshuabailes.
=> Add acquisitions project filter

tock/hours/tests/test_models.py, tock/hours/tests/test_views.py, tock/hours/views.py
Adds the `project_id` attribute from the `Project` class to the `SlimBulkTimecardSerializer` per @HuixianXu's request. Tests updated to reflect addition.
While making change, updated two failing tests to rely on UTC time, instead of local.
=> Update slim report

requirements.txt
Ref https://gemnasium.com/github.com/18F/tock/alerts and https://www.djangoproject.com/weblog/2017/apr/04/security-releases/
=> Upgrade Django to 1.10.7 to fix potential vulnerabilities

tock/hours/forms.py
Changes hours increment on timecard form from 0.25 to 0.50. The built-in widget enforces the increment on submit.
=> change hours increment on timecard_form

tock/hours/tests/test_views.py, tock/hours/views.py
Addresses #628 by automatically creating a new `ReportingPeriod` if the `end_date` attribute of the latest `ReportingPeriod` has passed. The new `ReportingPeriod` will have a `start_date` that is one day after the `end_date` of the previous reporting period (with it's own `end_date` six days after that).
To avoid situations where a new `ReportingPeriod` is created that includes work week days in more than one fiscal year, auto-creation is disabled for any potential start dates seven days before and after October 1st of any year, as long as October first is _not_ on a weekend. For instance, auto-creation would be disabled for the last week of September 2015 and first week of October 2015. 
Auto-creation will remain active in the last week of September 2017 and first week of October 2017 …
=> Trigger creation of reporting period if last reporting has ended (usually)

tock/hours/tests/test_views.py, tock/hours/views.py
I noticed that when this week's reporting period auto-created it had a Sunday end date (7/30) instead of a Saturday end date (7/29). Fix was a one liner, switching a `timedelta()` to `6` instead of `7` days, plus a test to verify success.
=> new end date should be six days from start date, not seven

tock/hours/views.py
Somehow #645 did not include the change from `import datetime` to `import datetime as dt`. This fixes the issue.
=> Fix datetime naming issue

tock/tock/templates/hours/timecard_form.html
Resolves #643 by building an id from an existing `forloop` variable and some static text, then set it as the `for` value for the label.
=> Fix delete checkbox label

tock/tock/utils.py
This changeset alleviates an immediate issue with not being able to debug/test Tock locally without a Float API key.  This is not quite an ideal fix, but it addresses an immediate need until more time can be spent shoring this up a bit.
=> Add a stop gap for checking the FLOAT API key

.circleci/config.yml
This adds support for running continuous integration on Tock via CircleCI (instead of Travis, which 18F will be dropping support for in coming months).
I've forked this repo to my personal account and you can see it running here: https://circleci.com/gh/toolness/tock/2
=> Add CircleCI support.

README.md, tock/tock/static/js/components/notifications.js, tock/tock/templates/base.html
Pop-up a browser notification in browsers that support it, at 3pm local time on Fridays.  Useful for people who leave Tock open all the time.
* The notification is currently flagged with `requireInteraction`, which means it requires the user to click to dismiss it.  I enabled that because it's my personal preference, but I recognize it might be more universally preferred for it to just go away on its own after a few seconds (whatever the browser does by default).
* Doesn't take into account folks on alternate work schedules
=> Add browser notifications for 3pm local time on Friday

tock/tock/templates/hours/timecard_form.html
Fixes issue #651
This changeset addresses an issue where the project category labels are included in the search for a project.  These categories cannot be selected and cause issues when trying to find a project that contains the same word in its name.
This change is the result of discovering an [undocumented option](https://github.com/harvesthq/chosen/issues/2752) with the [Chosen](https://harvesthq.github.io/chosen/) utility (specifically, [this one](https://github.com/harvesthq/chosen/pull/1343/files#diff-a3162852f1360124c43007c8130261dcR30)) that affects the items searched for in the search box that appears.
=> Disable searching for project categories

tock/hours/float.py, tock/tock/templates/hours/timecard_form.html, tock/tock/utils.py
Fixes issue #669 
This changeset provides much more robust error handling for the Float API calls and more graceful handling of them so that users can still see and enter their timecards.  If an error occurs while accessing Float data, the user is presented with a message saying so and the error is logged behind the scenes so we can see what went wrong and why.  We currently only see a stack trace saying that we cannot call a method on a NoneType object.
There's more to be done here for the future, but at this point we just need to make sure the timecards always work regardless of whether or not retrieving the Float data does and, in the case of such errors, where the breakdown actually happened and why.
=> Handling Float API errors gracefully

newrelic.ini
Tock does not currently have priveleges for high security in New Relic, so we are turning it off for the time being.
=> Shut off New Relic High Security

tock/tock/templates/hours/reports_list.html
This changeset adds links to make FY18 data as a standalone.  Note that a more in-depth fix will need to be made to ensure that things like the FY17 reports contain just FY17 data as right now they will still pull in FY18 data as well.
=> Enable FY18-only reports

tock/tock/templates/hours/timecard_form.html
Fixes #685
This changeset fixes an issue with the `label` element associated with the delete checkboxes, specifically when adding a new item.  The new items were not properly updating the `for` attribute in the `label` associated with the delete checkbox.
h/t to @hbillings for flagging this!
=> Fix ID mismatch with label element

tock/hours/tests/test_views.py, tock/hours/views.py
Fixes #692
This changeset adds a bit of extra error handling when trying to access timecards that are associated with reporting periods that do not exist, e.g., trying to fill out a future timecard that has not been officially opened yet.
h/t to @jmcarp and @tbaxter-18f for reporting this issue!
=> Fixes server errors when trying to access non-existent reporting periods

tock/hours/tests/test_models.py, tock/projects/models.py
Addresses #688
This changeset adds a `ProjectManager` model manager (not a human being...) for the `Project` model that provides a couple of convenience methods for easily retrieving all active and inactive projects.  The Project admin page already has the filtering exposed for inactive and active projects, but this will be needed when we start adding support to pre-populate time cards and only want to work through a list of active projects.
=> Add helper methods for filtering projects

.circleci/config.yml, README.md, runtime.txt, tock/tock/templates/hours/timecard_form.html
Part of #687 
This changeset adds a link to the [Tock handbook page](https://handbook.18f.gov/tock/) in the README and the timecard form itself.  In the case of the timecard form, it is a hardcoded info message that will appear below every other message to ensure that important and especially critical things are not missed:
CircleCI and cloud.gov have recently updated their container/buildpack versions as well, which means we can use Python 3.6.4.  This changeset accounts for that as well.
=> Add handbook page link and update Python to 3.6.4

runtime.txt
It turns out that the latest Python buildpack for Cloud Foundry is not deployed in cloud.gov just yet, so we need to go back one patch level version for Python.
=> Revert Python version for CF buildpack

Procfile, manifest.yml
This timeout is arbitrarily set at two minutes to allow for long API requests for timecard data that may take longer than 30 seconds. 30 seconds was the default coming from gunicorn after #708
=> Update timeout for gunicorn

.circleci/config.yml
This updates the `deploy_to_production` job to use the correct org and space for the deployer credentials for production.
cc: @ccostino
=> Fix production tag deployments

.circleci/config.yml, docs/deploy.md, tock/tock/context_processors.py, tock/tock/settings/base.py, tock/tock/templates/base.html
Helpful after #652 and #712 to show what version is currently deployed to staging and production. 
* Check the footer for a link to the mainline branch if on staging 
* Check the footer for a link to a GitHub release if on production
=> Add link to latest release in footer

.cfignore, .gitattributes, package-lock.json, package.json
- https://github.com/sass/node-sass/pull/2170#issuecomment-347845532
Addresses https://gemnasium.com/github.com/18F/tock/alerts
=> Update Node dependencies

tock/hours/tests/test_views.py, tock/utilization/tests/test_views.py
**Note: This is a PR against #720, not `master`.**
This fixes the hours and utilization view tests that aren't API-related.
I wasn't sure what to do about the views that seem to behave like API views: in the legacy version of the app, these views seem to have been protected by token-based auth, but now they have `@login_required` decorators around them, which suggests that they have cookie-based auth, and I'm not sure if that is actually what we want.  If it _is_ what we want, then I can fix these tests to work properly, but if it's _not_ what we want, I guess we should remove the `@login_required` decorators from the relevant views and have their auth managed by Django Rest Framework.  Um, I think.
=> Fix non-API hours and utilization view tests.

tock/hours/tests/test_views.py, tock/hours/views.py, tock/tock/settings/base.py
**Note: This is a PR against #720, not `master`.**
This follows up on #726 to make the API views of `hours` (which deliver CSV content rather than HTML) use [DRF's `api_view` decorator](http://www.django-rest-framework.org/api-guide/views/#api_view) instead of `login_required`.
Crucially, they also modify the app's DRF settings to use [`SessionAuthentication`](http://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication), in addition to the existing [`TokenAuthentication`](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication), which makes it possible for the endpoints to be accessed by both programmatic API clients (via `TokenAuthentication`) _and_ website visitors (via `SessionAuthentication`).
=> Convert hours API endpoints to be DRF API views.

tock/tock/tests/test_admin.py, tock/tock/urls.py
**Note: This is a PR against #729, not `master`.**
This fixes login in a way similar to what we did for CALC.  It contains a simplified version of the [`staff_login_required`](https://github.com/18F/calc/blob/develop/hourglass/decorators.py) decorator that we used in CALC.
Thoughts @rogeruiz ?
=> Redirect /admin/login to UAA, return 403 if not staff.

tock/hours/tests/test_views.py, tock/hours/views.py, tock/projects/tests.py, tock/projects/views.py, tock/tock/tests/test_admin.py, tock/tock/tests/test_url_auth.py, tock/tock/urls.py, tock/utilization/views.py
**Note: This PR is against #720, not `master`.**
This adds a test suite that ensures that most URLs are protected by auth, fixing #728.
To run it, use:
```
python manage.py test tock.tests.test_url_auth
```
* This test suite finds URLs by digging into Django internals a bit, specifically [`django.core.urlresolvers`](https://docs.djangoproject.com/en/1.9/_modules/django/core/urlresolvers/).  It's likely that this will break when upgrading to new versions of Django, which is probably OK; this test  suite doesn't need to last forever, but it's particularly important for #720.
The view at `/reports/2018-01-01/` doesn't have a `PermissionMixin`, nor does it have the `permission_classes` property like a lot of other `ListView` subclasses do.
Aside from that, this view is raising a …
=> Add test suite to ensure most URLs are protected by auth.

tock/hours/views.py, tock/tock/settings/base.py, tock/tock/templates/403.html, tock/tock/templates/404.html, tock/tock/templates/500.html, tock/tock/templates/uaa_client/login_error.html, tock/tock/urls.py, tock/tock/utils.py, tock/tock/views.py
**This branch is to be merged into #720 and not `master`.**
[This work refactors the error states](https://github.com/18F/tock/pull/730#issuecomment-370475323) and leaves the any files touched linted into a better state then how they were found.
=> Add error views instead of reusing login_error.html

tock/tock/settings/dev.py
This fixes #738 by setting `SECRET_KEY` to a constant value of `"development_mode"` during development.  Without this, `SECRET_KEY` defaults to a random 50-byte string, which means that whenever the dev server reloads due to a code change, the session (which I think is held on the client side and signed with the secret) gets invalidated.
=> In dev mode, set SECRET_KEY to constant value

requirements-dev.txt, requirements.txt, tock/hours/forms.py, tock/hours/tests/test_views.py
This moves us closer to #699 by upgrading us to Django 1.11.  From there we will be able to upgrade to yet another version of Django, the infamous 2.0!
* In order to properly use the changes in this new PR, Docker users will have to run `docker-compose build`, while non-Docker users will need to re-run `pip install -r requirements.txt`.  **To avoid confusion, we should mention this on Slack as soon as this PR is merged.**
* As @ccostino noted in https://github.com/18F/tock/issues/699#issuecomment-359467001, the select widgets in the timecard form are broken. This is because we have a custom subclass of `forms.widgets.Select` called `SelectWithData` which needed to be upgraded to use [Django's  new form rendering API](https://docs.djangoproject.com/en/2.0/ref/forms/renderers/). …
=> Upgrade to Django 1 11

api-docs/projects.md, tock/api/tests.py, tock/api/views.py, tock/hours/fixtures/timecards.json
Fixes #756.
**Update:**
I emailed the GSA's Chief Privacy Officer about this and he said:
> Current GS level is considered "releaseable" under GSA Policy, meaning that it is not confidential/sensitive info:  https://insite.gsa.gov/portal/content/674050
So we should be good to go!
=> Include 'grade' in timecards.json response.

README.md
Small tweak for https://github.com/18F/tock/issues/733#issuecomment-370942684
To create a development admin account, users should call ``createsuperuser`` with a non-email username.
Manually inserting an email username breaks ``utilization.GroupUtilizationView.get_queryset`` as email addresses are not caught by the current regex for the ``reports:ReportingPeriodUserDetailView`` urlpattern.
Not expected to encounter non-conforming usernames outside of development as ``@DOMAIN`` is truncated on user creation. There's only a single authorized domain at the moment,  this approach may lead to issues down the line if/when others are added.
=> Update Getting Started w/ valid username

tock/tock/settings/dev.py
Fixing debug-toolbar per #700.
Latest version (1.9.1) of debug-toolbar handles ajax requests in the middleware. Special handling for them no longer required in `show_django_debug_toolbar`
https://django-debug-toolbar.readthedocs.io/en/1.9.1/configuration.html#debug-toolbar-config
=> Update debug-toolbar config

manifest-production.yml, manifest-staging.yml
:eyes: http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated
`cf push` complained about it here.
```shell
Using manifest file manifest-${ENVIRONMENT}.yml
Deprecation warning: Specifying app manifest attributes at the top level is deprecated. Found: buildpack, timeout, memory, path, stack.
Please see http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.
```
=> Refactor manifests away from deprecated changes

.circleci/config.yml
This work should be recycling the production instances of Tock on a schedule at 5am every day. This should cause no downtime as it uses [the CF Recycle plugin](https://github.com/rogeruiz/cf-recycle-plugin).
=> Recycle production instances on a schedule

.cfignore, .circleci/config.yml, Dockerfile, Pipfile.lock, docker-compose.yml, requirements.txt
This changeset updates Django to the latest security release for 1.11, and accounts for several other system-level dependencies with the Docker and CircleCI configurations to make sure things are kept up to date with recent security releases.
=> Update Django and several project-related dependencies

.cfignore
This changeset restores the `requirements.txt` file to be read by Cloud Foundry with the Python buildpack to account for a `pipenv` issue currently taking place, which breaks deployments.
=> Remove requirements.txt from .cfignore

docs/authentication.md
A few minor grammatical/stylistic edits to the Authentication page. Note: For all of this documentation, I'm keeping main page titles in title case, subheads in sentence case.
=> Minor grammatical/stylistic edits

tock/hours/views.py, tock/tock/templates/hours/reports_list.html
This changeset adds a bit of flexibility to the snippets report to include additional project line items instead of just the old General line item.  The reason for this is once the General project was retired in favor of the newer non-billable project line items, the report lost its usefulness and would not display any of the new information.  If we ever want to add additional projects to this report, it should just be a matter of including the project ID with the newly defined constant.
=> Add support for additional non-billable projects for the snippets report

docs/offboarding.md
Standardizing punctuation within the checklist + adding one little bit to the contextual copy preceding the checklist.
=> Contextual copy + punctuation updates

tock/tock/settings/base.py, tock/tock/signals.py, tock/tock/tests/test_views.py, tock/tock/views.py
This addresses #810 with the following solution.
```
If the user is authenticated
Clear Django user session
Redirect to UAA server with Client ID and Redirect parameters
Redirect to application logout page
If the user isn't authenticated
Show the application logout page
```
=> Terminate all UAA sessions at the server level

tock/tock/remote_user_auth.py, tock/tock/templates/403.html, tock/tock/tests/test_remote_user_auth.py, tock/tock/tests/test_views.py, tock/tock/views.py
For #825, deny access by and provide a help message to users with inactive accounts.
Prevents inactive users from completing authentication w/ tock backend.
=> Raise PermissionDenied for inactive user accounts

tock/employees/models.py, tock/employees/tests/test_models.py
Modifies `is_late` to check for `is_billable`
Also includes some test tidying.
=> Modified is_late to check is_billable

docs/deployment-process.md, tock/maintenance_page/index.html, tock/maintenance_page/manifest.yml
For #806, providing a simple static app, `tock-maintenance` , to be deployed in the `prod` space which displays a barebones page for maintenance mode.
Maintenance mode will need to be enabled manually by re-mapping the production route to this static app. Disabling maintenance mode will be done by an automatic release which maps the production route or again manually.
Displayed maintenance page:
=> Provide static app for maintenance mode

tock/hours/views.py
For #834, fetching `TimeCardObjects` from non-billable projects directly from DB without a hard-coded list of `ids`.
=> Remove hardcoding from non-billable snippet fetch

tock/tock/templates/hours/timecard_form.html
For #849, update attribute reference in `timecard_form.html` template to render HTML generated from TimeCardNote markdown.
=> Display rendered markdown for timecard notes

tock/api/tests.py, tock/api/views.py, tock/employees/tests/test_models.py, tock/hours/models.py, tock/hours/tests/test_models.py, tock/hours/tests/test_views.py, tock/hours/views.py, tock/tock/templates/hours/reporting_period_detail.html, tock/tock/templates/hours/reports_list.html
See Issue #680 
I also added a few static methods to figure out the actual fiscal year start and end date based on the discussion I have with Jackie.
>During the week that spans two fiscal years, with the five work days, charging will happen to the year that has more days in it. So, if there are three or more September work days, the week will belong to the year September is in, else, if there are more October work days (three or more), this week will belong to the year October is in.
* Notes
* ~~There seems to be an inconsistency with the date in the report for FY2016.  The superuser report starts with 10/1/2016, but other reports starts with 10/2/2016.  10/1/2016 is a Saturday so I …
=> Issue 680: Fix FY reports to only include specific years

.circleci/config.yml
We're having an issue with #772 where it's consuming too many containers because it gets stuck. This tries to limit recycling production instances based on changes to the Tock release tag. So instead of running on all branches, it'll only target one tag at a time.
- n/a
=> Only recycle based on tags instead of all branches

docs/local-development.md
Copying the commands with $ at the start does not work. In other examples, $ is not added to represent shell.
=> removed un-needed $ from commands

tock/tock/settings/base.py
Follow-up for #922, enabling the [SecurityMiddleware](https://docs.djangoproject.com/en/2.2/ref/middleware/#module-django.middleware.security) allowing us to set the HSTS headers as expected.
=> Enable SecurityMiddleware

tock/hours/forms.py, tock/tock/templates/hours/timecard_form.html
Working towards resolution of #885, we're making incremental improvements to the error messaging on timecard submission.
Specifically:
- Project names are now included in each error message
- Each error message links within-page to the referenced project
- Removed repeated rendering of messages/errors at bottom of the page
=> Clarify timecard validation errors

tock/tock/templates/employees/user_recent_tocks.html
Continuation of #927, removing errant context variable rendering on page and revising `url` templatetag a bit, it was previously not rendering the expected link.
=> Cleaning up the recent tock table template

.circleci/config.yml
Regarding #943.
CircleCI tweaks to simplify, modernize, and improve usage of CircleCI: 
- 86cb3e6: Removes `working_directory` configuration, as it is [no longer required](https://discuss.circleci.com/t/working-directory-is-no-longer-required-defaults-to-project/14363).
- b098d3d: Use `npm ci` over `npm install`.
- 5804efc: Wait for a server on port 8000 instead of sleeping for 5 seconds.
This PR does not address deployment issues, will follow-up with an additional PR around deploys.
=> Tweak CircleCI configuration for builds.

.circleci/config.yml
Related to #943.
Rolling-restart is more recently maintained, is the original fork, and works with the latest CF CLI for when we upgrade. 
It’s a bit of a shot-in-the-dark here since I don’t 100% understand what’s going on — the `cf-recycle-plugin` plugin isn’t correctly detecting process restarts. I had thought this was due to conflicting recycle jobs — one job was recycling a process out from the other — but since removing the concurrent jobs, the issue is not fixed. 
Looking at [this morning’s run](https://circleci.com/gh/18F/tock/5417), the CircleCI job output seems to indicate that Instance 0 was never restarted, which caused the job to timeout. However, looking [at the cell restart logs](https://logs.fr.cloud.gov/app/kibana#/dashboard/App-Overview?_g=(refreshInterval:(pause:!t,value: …
=> Use cf-rolling-restart over cf-recycle-plugin.

docs/README.md, docs/utilization.md
For #981, initial pass at a plain language description of how Tock is currently reporting on utilization.
=> Add initial docs for utilization reports

tock/tock/templates/utilization/includes/unit_utilization_cell.html, tock/utilization/employee.py, tock/utilization/org.py, tock/utilization/tests/test_views.py, tock/utilization/unit.py
Resolves #1022, correcting utilization aggregations and display to render `target` hours as the denominator and for use in utilization calculations.
=> Utilization should use target hours as denominator

tock/utilization/tests/test_views.py, tock/utilization/views.py
Resolves #1026 by removing the `is_staff` check and updating test to access this view as a non-staff user.
=> Remove is_staff check for GroupUtilizationView

tock/employees/views.py, tock/utilization/tests/test_views.py, tock/utilization/utils.py
Resolves #1033 and part of #1034 by removing the check for `is_billable=True` when generating utilization data.
Also includes a minor tweak to reduce number of database queries when rendering UserDetail view.
=> Include all active users in utilization reports

docs/utilization.md, tock/hours/models.py, tock/tock/templates/utilization/group_utilization.html, tock/tock/templates/utilization/includes/unit_utilization_cell.html, tock/utilization/utils.py
Resolves #1036 by differentiating between situations where no timecard data is available
and the available timecard data indicates a `target_hours` of 0. Target hours of zero indicates a `non-billable` staff member, denote as such but still render counts as they contribute to overall numbers.
**Note: Targeting `billable-as-property` branch, re-target to master if that is merged first**
Included a documentation update w/ example to help clarify.
=> An undefined amount of tocking

tock/api/views.py
Unblocking progress on #1052, this fixes the UserData API endpoint by properly handling serialization of the `Unit` attribute as it was recently moved from a string to it's own table in the database.
=> Update UserData serializer for Unit obj

tock/organizations/admin.py
Improves business unit admin view by including each BU's Organization in the list view. Units can also be filtered by Organization and `active` status.
https://github.com/18F/tock/issues/1021
=> Update Unit admin to include and filter on Organization

tock/hours/tests/test_views.py, tock/hours/views.py, tock/projects/fixtures/projects.json, tock/tock/templates/hours/reporting_period_user_detail.html
Makes the tables displayed in ReportingPeriodUserDetailView more readable and updates the utilization calculation to match other parts of the application.
resolves #1056 
resolves #1058
=> ReportingPeriodUserDetailView cleanup, utilization calculation update

tock/api/views.py, tock/employees/models.py, tock/employees/tests/test_models.py
Copies the `is_active` property from an associated `User` model into the `UserData` model, and updates the UserData API serializer to include that property. This could help with #1071, per @Jkrzy's comment in Slack.
=> Add is_active property to UserData model

tock/hours/views.py, tock/tock/static/js/components/filter_report_table.js, tock/tock/static/sass/core.scss, tock/tock/templates/hours/reporting_period_detail.html
Closes #968. Makes the unfiled timecards list filterable by their respective orgs. Looks like this...
Unfiltered:
Filtered:
=> Filter weekly reports by org

tock/tock/templates/_navigation.html
For #1112, we remove the `is_staff` check when rendering the `Reports` item in the navigation menu. All users have been able to access these reports but, until this PR the links to access them have been hidden to all but admins.
=> All users can access Reports navigation item

tock/tock/management/commands/load_timecard_utilization_data.py, tock/tock/management/commands/update_billable_expectations.py
For #1119, we expand our management command previously used to backfill billing targets for existing timecards with the ability to update `UserData.billable_expectation`. Also renamed the command to `update_billable_expectations` which is both a bit shorter and I think clearer as to it's purpose.
Example call:
```bash
python manage.py update_billable_expectations  aug20-backfill.csv -u
```
With a csv file structured as below:
```csv
user.name, 36, 07/04/2020
```
Results in all timecards for reporting periods after 7/4/20, as well as UserData.billable_expectation, being set to 36 hours for each `username` provided in the csv.
=> Enhance billable_expectation backfill management command

tock/tock/templates/utilization/utilization_analytics.html, tock/utilization/analytics.py, tock/utilization/views.py
This continues the pursuit of #1142 by adding utilization rate and OOO time to the billable hours graph and a second graph showing the number of distinct users by organization who are using tock over time.
A second data frame and plot are passed into the `utilization_analytics` template now. The utilization rate is presented as a second subplot above the billable and non-billable hours plot. The discovery of the third category of `excluded_hours` on each timecard gives a substantial improvement to the total hours graph over time by "filling in" the holidays with the corresponding increase in OOO time that is tocked.
=> U-rate and headcount graphs

tock/tock/templates/utilization/utilization_analytics.html, tock/utilization/views.py
Discussion on #1142  suggested using the past 12 months time frame by default. This changes the Analytics page to show the last year of data by default. It also adds a "tip" for the Start Date on what the earliest available data is.
"Previous year" is a surprisingly complicated concept (12 months, 365 days, 1 calendar year?). This just subtracts 1 from today's year.
=> Default to graphing past 12 months

Pipfile.lock, requirements.txt
Updating our python dependencies including the [latest Markdown](https://github.com/Python-Markdown/markdown/releases/tag/3.2.2) which resolves the import issue we're seeing with `importlib-metadata`
=> Update python dependencies

tock/hours/views.py, tock/projects/views.py, tock/tock/utils.py, tock/utilization/views.py
In  #1138  @jkrzy noticed that we were mis-using the `PermissionMixin` class with no `permission_classes` which restricts nothing. This corrects that by using `LoginRequiredMixin` in those cases and prevents it from happening again by making it an exception to use `PermissionMixin` without defining the `permission_classes` attribute.
We could go further with this and replace all of the correct uses of `PermissionMixin` with `permission_classes = (IsAuthenticated, )` by `LoginRequiredMixin` but I haven't done that here. I'm willing though if people would prefer it.
=> Fix our use of PermissionMixin

.circleci/config.yml, docs/deployment-process.md
For https://github.com/18F/tock/issues/1149,  we're updating our  circleci config to:
* Use [CircleCI convenience images ](https://circleci.com/docs/2.0/circleci-images/#circleci-base-image)
* Install the latest (v7) cloudfoundry CLI
* Handle deploys with `cf7 push --strategy rolling`
* Handle restarts with `cf7 restart --strategy rolling`
=> Use CF7 for rolling deploys and restarts

tock/api/tests.py, tock/api/views.py, tock/hours/views.py, tock/tock/templates/utilization/utilization_analytics.html, tock/utilization/analytics.py, tock/utilization/tests/test_views.py, tock/utilization/views.py
This adds the capability to look at Tock data at the level of a single organization. This is especially valuable because utilization rate makes the most sense for the 18F organization without mixing in cloud.gov, login.gov, CoE, etc.
There is a layout re-design for the form that selects orgs and dates to make it less intrusive on the space available for the graphs.  There is also a pesky `NULL` organization in the oldest tock data that needed special handling.
=> Utilization analytics by organization

tock/projects/admin.py
As requested by Matt Spencer, adding ID as a `Project` search field in the admin panel.
resolves #1173
=> Add ID as project search field

tock/tock/management/commands/update_billable_expectations.py
Resolves a bug in the `update_billable_expectations` management command, as described in #1183.
=> set billable hours, not billable expectation

tock/employees/admin.py, tock/tock/management/commands/update_billable_expectations.py
In https://github.com/18F/tock/pull/1189 we updated a management command to update `UserData.expected_billable_hours` but we did not _also_ update the value which was being saved there.
This PR changes the management command such that an integer is saved to `UserData.expected_billable_hours` as opposed to a decimal percentage of billable expectations. Allowing us to resolve https://github.com/18F/tock/issues/1183.
Also enables list-editing of billable targets in the UserAdmin list view.
=> Correct billable target updating management command and admin tweak

.circleci/config.yml
Update the circle ci config to pin npm to latest-6.
Reference: https://github.com/npm/cli/issues/2599
=> Specify npm version for CI

docs/deployment-process.md
We review the code
Really. We actually do.
It better be good!
Adding a section outlining how we do code review, so that this can be referred to from the SSP. (It's also useful to have it written down here.)
=> Add section on code review to deployment process docs.

tock/tock/templates/utilization/includes/unit_utilization_table.html, tock/utilization/unit.py
Resolves #1233 by adding `username` back to the report template context so it can be used to render the EmployeeDetail link. 
We're passing raw python structures to the template so we're building the urls in the template as opposed to using Django convenience methods like `.get_absolute_url`
=> Add username to utilization templates

tock/tock/static/js/components/timecard.js, tock/tock/tests/js/integration/timecard.test.js
This builds on the work of #1156, which was close but not quite there in terms of rooting out all the jquery on timecard.js. I looked briefly into just updating that PR, but with the accessibleAutocomplete change, it had drifted enough away from main that that would have been more difficult. Thanks for the work @hbillings and @jadudm 
This change:
1. Removes all code related to localStorage. Very happy to discuss this if anyone has feelings about it; Conversations with @Jkrzy have led me to believe that the cost in reasoning and brittleness is far greater than the benefits we're currently getting.
2. Removes all jquery in timecard.js
3. Reorganizes the code somewhat.
4. Adds JSDOC documentation to make the existing functions a bit more understandable.
5. Moves the test file into an …
=> Remove all jquery from timecard.js

tock/tock/static/js/components/timecard.js, tock/tock/tests/js/integration/timecard.test.js
When a new project line is added to a timecard the delete input must be unchecked.
My test here feels not great, would appreciate any recommendations to simplify where possible!
=> Clear delete inputs for newly added tock lines

tock/tock/static/js/components/timecard.js
Resolves #1244 wherein a friend of Tock noticed that project note fields were not being displayed on timecards when there were 10 or more project lines. 
When incrementing project element ids we now match the whole numeric id of the previous element.
=> Render note fields on timecards when there are more than 10 project lines

.circleci/config.yml, Pipfile, Pipfile.lock, runtime.txt
Moving to python 3.8.8 to match latest python_buildpack on cloud.gov
=> Bump python to 3.8.8

api-docs/README.md, api-docs/full-timecards.md, docs/local-development.md, tock/api/tests.py, tock/api/urls.py, tock/api/views.py, tock/hours/models.py
This addresses #1259 by adding a new endpoint to fetch Timecard data. It's ready for review, but I'm expecting we'll want to discuss some of the details of what exact data and query parameters to include.
This is based on some initial conversation in #1259. I didn't attempt to refactor any of the "timecard" vs "timecard object" verbiage in various API endpoints, serializers, or API views, though I'm definitely open to that idea. I did add some documentation around that in hopes of making that distinction clearer to future code readers and writers. As-is, I used "full timecard" to mean `Timecard` to disambiguate from the existing use of "timecard" referring to `TimecardObject`s (e.g. the existing `/timecards.json` endpoint returns `TimecardObject`s).
=> Add API endpoint for fetching timecard data

docs/diagrams/network.puml
Without showing ports
How will we know what's secure?
Add the port numbers.
During the SSP review we were asked to add `https (443)` to the logging connection lines in the network diagram. This commit adds that information in as minimal way as I could find.
=> Add “https (443)” to logging connections as per SSP review request.

README.md
Looks like Snyk's python vulnerability badge link changed. updating...
Snyk's python vulnerability badge link icon has been broken. This is the new link, according to Snyk.
=> Fix snyk badge link for python

tock/tock/remote_user_auth.py, tock/tock/utils.py, tock/tock/views.py
Resolves 1306
The issue was raised during the test prior to update Django to 3.0 using this command `python -Wa manage.py test` (please see issue 1306). I also did a folder-wide search for `logger.warn`, found one and changed (view.py)
=> Update 'warn' to 'warning' since 'warn' is being deprecated

docker-compose.yml, package-lock.json, package.json
This PR:
- Updates the version of Node.js used to run `sass` in development to 14.17.3 (latest LTS)
- Applies `npm audit fix` to update dependencies with vulnerabilities in a semver-compatible way
- Applies `npm audit fix --force` to update dependencies with vulnerabilities in a potentially non-semver compatible way
- Adds `node-notifier` as a dev dependency (this was previously directly depended on by Jest, but newer Jest versions only require it if you  are using `notify: true` in your jest.config.js [which we are]).
This is what `npm audit` looks like now:
```
$ npm audit
=== npm audit security report ===                        
found 0 vulnerabilities
in 658 scanned packages
```
This should close #1298 
I'd like to rebase #1297 on `main` after this lands and proceed with eliminating …
=> Npm audit / Node version update

.circleci/config.yml, Dockerfile, Pipfile, Pipfile.lock, docs/dependency-management.md, requirements.txt, runtime.txt
Update Dockerfile, cloud.gov buildpack, and Pipfile in lock step.
Updates Python used for development + production from 3.9.5 -> 3.9.6
Closes #1315 (note that [`python:buster`](https://hub.docker.com/layers/python/library/python/buster/images/sha256-780d55ef3a6171674be69ea95254e96b1996bed70884f7633f98f39a6671aa35?context=explore) is currently the same as [`python:3.9.6`](https://hub.docker.com/layers/python/library/python/3.9.6/images/sha256-780d55ef3a6171674be69ea95254e96b1996bed70884f7633f98f39a6671aa35?context=explore))
=> Python 3.9.6

Pipfile, Pipfile.lock
Our debug toolbar
Must be shown as more recent.
From “star” to precise.
Change version of django-debug-toolbar to be 3.2.1 at minimum.
This is for ATO support.
=> Make the pipfle(s) reflect minimum version for Django Debug Toolbar.

tock/hours/forms.py, tock/hours/tests/test_integration.py, tock/tock/static/js/components/timecard.js
The weekly billing code introduced a new (usually hidden) field on the timecard form and the Javascript was setting a value for that field which was confusing Django's built-in mechanism for detecting if form fields have changed. The observed bug was that on submitting the second time card, the `extra` field that Django added was giving a "This field is required" error.
This fixes the bug by changing `timecard.js` to leave that field unselected and it adds a test for submitting two time cards to make sure that the second one works.
=> Fix bug with not ignoring empty forms

docs/local-development.md
`docker-compose run` is required instead of just `docker run` when attempting to run the JS integration test suite. I encountered a docker failure message when trying to run the previous command. @matthinz pointed me in the right direction.
=> Fix docker syntax for JS test execution

tock/tock/static/js/components/timecard.js, tock/tock/static/sass/_entries.scss, tock/tock/templates/hours/timecard_form.html, tock/tock/tests/js/integration/timecard.test.js
Remove hourly summation elements if weekly billable project exists on timecard
The hourly summation elements in the footer should hide upon selection of a weekly billable project as well as being hidden when coming into a saved timecard that has a weekly billable project on it. Removing any weekly billable projects from the timecard either by deleting it or updating it should restore the hourly summation elements.
JS tests were added and were passing on my local machine but seem to fail when ran inside the docker instance, that probably needs its own issue.
=> Remove hourly summation elements if weekly billable project exists on timecard

tock/api/tests.py, tock/api/views.py, tock/utilization/tests/test_views.py, tock/utilization/utils.py
Addresses #1369. Update the scale/precision of the `project_allocation` field in the API return for Timecards. The `TimecardSerializer` just needed updated to reflect the scale and precision change that was made to support 12.5% (`0.125`) project allocation.
=> Update project_allocation API scale/precision

tock/tock/settings/production.py
The last PR made it so the `script-src` CSP policy was just the nonce rather than the allowed sources AND the nonce (which is needed to handle inline values.
=> explictly set csp for scripts so can have nonce add to list

.circleci/config.yml, docker-compose.yml
On cloud.gov, Tock is using postgres 12.8. This PR finishes the work from #1328 and #1330 by getting the local development environment synced up to the same version as the cloud.gov version.
Somewhere between postgres 9 and 12, they disabled password-less accounts by default. You can either re-enable them explicitly or you can give the default user a password as well. I opted to do the latter thing. It only shows up in the `docker-compose.yml` so it was really easy to do.
- closes #1328
- closes #1330
- closes #1329
- closes #1327
=> Update PostgreSQL images used in local development

tock/maintenance_page/manifest.yml
The `manifest.yml` for the Tock maintenance page currently specifies the `cflinuxfs2` build stack, but that hasn't been supported in cloud.gov for a while, so `cf push` fails. This PR updates the stack to `cflinuxfs3` to we can push this app again.
=> Fix the stack being referenced by the maintenance page

manifest-staging.yml
Currently, staging deployments use the app name `tock` instead of `tock-staging`. The documentation says to use `tock-staging`, and for safety's sake, that's what we'll do. This PR updates the manifest to use `tock-staging`.
=> Deploy to tock-staging in staging

tock/tock/static/js/components/save_csv.js, tock/utilization/templatetags/analytics.py
Tock's CSP policy disallows inline Javascript, so `onclick=""` attributes are forbidden. Those attributes are how CSV exports are triggered on the analytics page. The handler relies on a random pseudo ID that is generated at render time to identify the table being exported.
This PR removes the `onclick` attribute from the button, and adds `data-csv`, `data-csv-id`, and `data-csv-name` attributes. The `data-csv` attribute is just a flag that the button should act as a CSV exporter. `data-csv-id` and `data-csv-name` are populated with the pseudo ID and filename hint, respectively.
Then, after the DOM is loaded, this PR adds code that finds all button elements with a `data-csv` attribute. It iterates over them, pulling out their IDs and names, and adding a click event listener. It uses the …
=> Refactor the CSV export for CSP reasons

.circleci/config.yml, Dockerfile, Dockerfile-tests, Pipfile, Pipfile.lock, runtime.txt
Currently requires Python 3.10.1, which is too strict and doesn't allow for automatic upgrades to patch versions. 3.10.1 is no longer supported by the cloud.gov Python buildpack, so we need to bump it up anyway. Making the version requirement less strict should solve both problems.
=> Use a less strict python version

.circleci/config.yml
The `cf push` command in the CI job refers to an app that doesn't exist in the staging manifest file, so it hangs forever. This updates the `cf push` command to reflect the app name from the manifest file.
=> Harmonize app name, so it can actually go

tock/tock/static/js/components/save_csv.js, tock/utilization/templatetags/analytics.py
The data tables that can be downloaded are assigned a random ID by Django at runtime. These IDs are five-character alphanumeric strings that are HTML-valid. _However_, they can begin with numbers with makes them _invalid_ CSS selectors, so the `document.querySelectorAll` method rejects those IDs. Clicking the "Export CSV" button triggers a function that selects the table based on its ID; if the ID just happens to start with the number, it will throw an exception. If the ID happens to start with a letter, the CSV will download correctly.
Since the IDs are random, the bug is sporadic. In any case, make the IDs CSV-valid by prepending `table-` to the beginning of the ID instead of appending `-table` to the end. This way they will _always_ begin with a letter and will be queryable.
An …
=> Fix a bug with the CSV downloads

Pipfile, Pipfile.lock
Upgrades Django from 3.2.15 to 3.2.16 to resolve this dependabot security issue: https://github.com/18F/tock/security/dependabot/28
=> upgrade django to 3.2.16

docs/incident-response.md
We had to recently rotate CircleCI keys due to an [incident](https://circleci.com/blog/january-4-2023-security-alert/). Documenting the process for future incidents.
=> document CircleCI secret rotation

manifest-production.yml
Drop prod usage slightly to allow memory space to deploy application.
* see this: https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1673377439366699 Slack thread for more context.
=> drop memory usage for enough headroom to deploy

tock/api/tests.py, tock/api/views.py
Modify the TimecardSerializer in the API to return `billable_expectation`  and also remove some deprecated fields.
Fixes https://github.com/18F/tock/issues/1504
=> reporting_period_audit API: billable_expectation

.github/workflows/on-add-issue.yml
This code adds a GitHub Action that runs when a new issue is opened in this repo.
The GitHub Action populate the issue onto the Delivery Assurance [projects board](https://github.com/orgs/18F/projects/41) without a status where it will be ready to be prioritized or removed.
This is part of https://github.com/18F/delivery-assurance/issues/9 and closes #1540
=> Add GitHub action to run when issues are opened

Pipfile, Pipfile.lock
Upgrade to Django 3.2.18 to fix dependabot security alerts
=> upgrade to django 3.2.18

docs/local-development.md, tock/hours/forms.py, tock/hours/tests/test_forms.py, tock/hours/tests/test_integration.py
Partially fixes https://github.com/18F/tock/issues/1575 by adjusting the backend (and tests) to fail form submission if hourly data is submitted for a weekly project, or vice versa. 
Ideally the user should never see this message, as the front end will clean up project selection values, but _if_ the javascript fails and the user happens to submit mixed hourly/weekly data, here are the error(s) they will see:
=> Validate billing based on project weekly/hourly status

tock/tock/static/js/components/timecard.js
Clear hours field on the front-end when weekly billing project is selected. It was reported in issue #1575
=> Fix hours field to clear the number when a weekly project is selected

Pipfile, Pipfile.lock
Pin codecov to `2.1.13` due to `2.1.12` being pulled from pypi. See https://about.codecov.io/blog/message-regarding-the-pypi-package/ for the details.
=> pin codecov to 2.1.13

tock/utilization/tests/test_views.py
Adds tests to `utilization/tests/test_views.py` that incorporate weekly billing. Currently, the calculation of an individual / organization's utilization does not take into account billable weekly allocation. These tests are intended to confirm the expected behavior of utilization ignoring weekly billing.
- adds more setup by way of projects, users, and timecards
- amends unsubmitted test to include newly added timecards
- tests that a billable weekly project with no additional hours will consider utilization as 'No hours submitted.'
- tests that weekly + hourly calculates utilization only with hours
Closes https://github.com/18F/tock/issues/1590 
This is part of the [utilization epic](https://github.com/18F/tock/issues/1500)
(Tagging @alexbielen and @kingcomma from the TLC crew for their …
=> Utilization test util view

tock/hours/models.py, tock/hours/tests/test_models.py, tock/projects/fixtures/projects.json, tock/utilization/tests/test_views.py
Incorporates weekly allocation into the `Timecard.utilization` field calculation. Closes https://github.com/18F/tock/issues/1591. Follow-on work is planned for utilizing this new calculation in reports and views (#1592).
Changes the following logic in the `Timecard` model:
- `total_weekly_allocation` considers billable weekly projects only
- `target_hours` is now based on the `HOURS_IN_A_REGULAR_WORK_WEEK` setting and no longer on the sum of billable and non-billable hours (which could be zero for users on weekly billing projects)
- `utilization` calculation sums `total_weekly_allocation` and hourly utilization (`billable_hours`/`target_hours`)
Updates existing tests to accomodate utilization changes and adds:
- test fixture for non-billable weekly project
- test for no billable hours nor …
=> calculates timecard utilization including weekly allocation

manifest-staging.yml, tock/maintenance_page/manifest.yml
Change stack to cflinuxfs4 at staging and maintenance page
* Relevant research and support documents: Following [cloud.gov instructions](https://cloud.gov/2023/04/27/cflinuxfs3-deprecation-update/)
=> Change stack to cflinuxfs4 at staging and maintenance page

tock/hours/tests/test_models.py, tock/projects/fixtures/projects.json
Adds additional utilization tests for common business cases:
- Timecard with many weekly billing projects (e.g., an AM)
- Timecards with 40 hours of out of office time
- Timecards with billable expectations < .8
Closes #1607
=> Add additional utilization tests for common business cases

tock/hours/tests/test_views.py, tock/hours/views.py, tock/tock/templates/employees/user_recent_tocks.html, tock/tock/templates/hours/reporting_period_user_detail.html
adds or updates a timecard's weekly allocation amount to the UI
updates view test to include allocation total
On the recent timecards view, I added weekly allocation which ONLY includes billable weekly allocation (comes from the timecard model).
Note: there was already an existing allocation field on the `reporting_period_user_detail` page which includes both billable and non-billable allocation (the info comes from the timecardobject model).  However, at the bottom where information is provided to explain the utilization calculation, only billable allocation is included. To distinguish, I left the top "project allocation" and made the bottom "billable allocation"
=> Utilization detail view

tock/hours/models.py, tock/hours/tests/test_models.py
Changes a timecard's `total_allocation_hours` calculation. Previously, this used a hardcoded value from `base.py` (currently 32 hrs). Instead, we start with the timecard's `target_hours` before multiplying that by the (billable) weekly allocation percentage to create an estimate of the allocation hours.
Closes https://github.com/18F/tock/issues/1612
`base.py` still contains `FULLTIME_ALLOCATION_HOURS` as a setting, as it is used in a migration. If not for the migration, it could be removed.
=> updates timecard allocation hours calculation

Pipfile, Pipfile.lock
Upgrade Pipfile.lock -- this process also includes up-to-date updates of other packages such as `requests`.
=> Pipfile: upgrade django to 3.2.19

tock/hours/models.py, tock/hours/tests/test_models.py
Previously, we changed `total_allocation_hours` (an estimate of how many hours a person with weekly allocation % spent working on the project) to use `target_hours` in its calculation. This worked great for individuals with a .8 billable expectation, but not so well for folks like supervisors with a .4 billable expectation, as it then halved their potentially contributed hours.
Here is a new proposal for the `total_allocation_hours` estimate that returns to the assumption that there is a set number of hours that people would be likely to bill during the week (current values are 32 hours / .8 billable expectation, set in `base.py`), and that a person's allocation % is a percentage of THAT time.  Therefore, we use the default billable expectation to compare allocation %s against.
This adds …
=> changes weekly allocation hour estimate calculation

docs/utilization.md
Aligns `docs/utilization.md` with recently updated behavior to include weekly billing projects in utilization rate calculations (see #1591 and #1618). Also includes some clean up to consistently handle capitalization, pseudo-code, and variable names.
Closes #1611 
Would appreciate a gut check on whether or not the "Weeks 1-4" example is unwieldy now. It's the only example that uses anything other than simple arithmetic.
=> Updates to utilization documentation with definitions and examples for weekly billing

.profile, manifest-staging.yml
Trying to simplify the current egress workflow by adding two environment variables:
- `https_proxy` will be set to `egress_proxy` when the app launches
- `REQUESTS_CA_BUNDLE` will force the python libraries to load system ca certificates
=> setup egress environment vars

tock/api/views.py, tock/hours/tests/test_views.py
when the API emits an error, escape all user input (query params).
this behavior was flagged in a netsparker scan, but it's a false warning. nonetheless, let's fix anyway in the name of sanitizing output.
=> api: escape query params when emitting error

Pipfile, Pipfile.lock
As mentioned in https://github.com/18F/tock/pull/1658#issuecomment-1682936443 a sub-dependency is raising a flag on Snyk review. 
> For the record, forcing a pass for the snyk check since the vulnerability is in setuptools, which is already at the latest version -- indeed, the explicit fix is to `Pin setuptools to version 65.5.1` ; iow, zope.event here is a false positive.
> 
> ```
> Introduced through zope.event@5.0
> Fixed in setuptools@65.5.1
> ```
Tock use `pipenv` which do not provide a way to override that sub-dependency. But the maintainer offered a [workaround](https://github.com/pypa/pipenv/issues/1921#issuecomment-379131833). 
This PR uses that workaround. A long-term fix to this issue could be the use of pyproject.toml, a new [unified Python project settings …
=> Workaround to override zope sub-dependency

tock/tock/static/js/components/timecard.js, tock/tock/tests/js/integration/timecard.test.js
To close #1638, the Total hours counter is always visible in this PR. The color was changed to grey while billing hours remained the same.
=> Add Total Hours Counter even with Weekly Billing Projects in Reporting Period Page #1638

tock/tock/static/js/components/timecard.js, tock/tock/tests/js/integration/timecard.test.js, tock/utilization/tests/test_views.py
Remove the total counter for weekly billing. Another PR is being prepared with an improved total hours algorithm for weekly billing. 
* Tests
=> Remove total counter on weekly billing

docs/backup-and-restore-database.md
Adds documentation for importing data into docker and clarifies a few steps of the export process.
Please confirm that none of the information that I included in the documentation is sensitive. I believe that it is largely docker-compose defined.
Most of this documentation is taken straight from notes that @kingcomma put together when working on Tock.
=> adds documentation for importing data into docker

tock/employees/models.py, tock/hours/tests/test_views.py, tock/hours/views.py, tock/tock/templates/hours/reports_list.html
Adds fields to the "complete timecard data" report.
| Field           | Type            | Description | 
| ----------- | ----------- | ----------- | 
| is_weekly_bill | boolean | True if weekly billing, false if hourly project |
| project_allocation | decimal 0 - 1| Weekly billing allocation (50% is .5, 100% is 1, etc)|
| billable_expectation | decimal 0 - 1 | The % of a week expected to be spent on billable work (.8 == 32 hours) |
| target_hours | decimal | Estimated hours that should be billed to a project (based on expectation, OOO time, etc) |
| employee_unit | string | Chapter or other inter-org component (ex: 18F engineering) | 
These fields allow for analysis not currently possible through the reports, such as whether a person staff person
was likely FT or PT during a given week on …
=> Timecard report fields

tock/hours/forms.py, tock/hours/tests/test_forms.py
#1728 was tracked down to a situation where the timecard form might submit "0" for project allocation even for hourly billing projects. This changes the form cleaning code to allow that possibility without raising the error message from the bug.
We add a test for the situation that fails in our current code and passes with the fix.
There are a couple unrelated changes where `or None` was removed where it wasn't doing anything.
Fixes #1728
=> Allow zero for project allocation on hourly projects

tock/projects/tests.py, tock/utilization/analytics.py
#1615 tracked down a situation where the individual project view can fail when a timecard object has `None` for the `hours_spent` field. This is uncommon, but does happen in our production data.
This fixes that situation by filling with `None`s in the data frame with zeroes which is the more common case for our data.
There is a failing test case that fails without the fix and passes with this change.
=> Fix projects view when timecards have None hours_spent

bin/run.sh
This is one step towards #1695. New Relic doesn't appear to respect the `https_proxy` environment variable, so we specify it explicitly when we call `newrelic-admin`.
This appears to fix New Relic's stopping of deploy when we remove the public egress security group, as long as the proxy is correctly configured.
=> Tell New Relic to use our proxy

manifest-production.yml
We forgot to add this environment variable for production (this was already set in staging). This env var allows python libraries to pick up the system ssl certificates on the cloud.gov instance.
=> add REQUESTS_CA_BUNDLE env var to prod

tock/utilization/analytics.py, tock/utilization/views.py
This attempts to resolve #1642 
* For a project view (/projects/{pk_id}), we were previously formatting the total hours in the data table using `:.0f`, I've updated that to format using `:.2f` instead. This seems to correctly stop truncating hours and the test suite passes.
* The original ticket also mentions `DataTable.applymap()` being deprecated and replaced by `DataTable.map()`. I found that `DataTable.map()` was already being used in the [utilization/analytics.py](https://github.com/18F/tock/blob/main/tock/utilization/analytics.py) file but the terminal complained about `DataTable.applymap()` in [utilization/views.py on line 187](https://github.com/18F/tock/blob/main/tock/utilization/views.py#L187), I've replaced `DataTable.applymap()` …
=> Replace deprecated applymap() and use two decimal places for formatting

tock/tock/middleware.py, tock/tock/settings/base.py
Added NoCacheMiddleware in response of a pentest finding.
=> Added NoCacheMiddleware

docs/deployment-process.md
Docs-only: Fix up the deployment process document to replace a broken URL, correct some Cloud Foundry space and app information, and make a couple of other minor edits.
Relates to my Tock onboarding issue, https://github.com/18F/tock/issues/1801.
=> Update deployment process docs

tock/hours/views.py, tock/tock/templates/hours/reporting_period_list.html
Reverses the order of uncompleted reporting periods and bolds the current week.
This is a solution to #1770, but not the one that was suggested and mocked up for reasons described [here](https://github.com/18F/tock/issues/1770#issuecomment-2394308218).
=> Emphasize current reporting period and reverse order

docs/README.md, docs/deployment-process.md, egress_proxy/tock.vars.yml, manifest-production.yml, manifest-staging.yml
Make two configuration changes in the New Relic agent configuration:
- Configure the Python agent to send data to `gov-collector.newrelic.com` to ensure FedRAMP compliance.
- Add the `gov-collector.newrelic.com` endpoint to Tock's egress proxy allow list, which should enable the Python agent to report APM data to New Relic again.
We are recording Deployment events successfully because Tock sends them via the `newrelic_admin` script. It sends data to `api.newrelic.com`, which we've already allowed through the egress proxy and which doesn't require a FedRAMP-specific setting.
Resolves #1792.
The change in system behavior can only be confirmed in a deployed environment with an egress proxy.
Review that the egress proxy configuration change is unlikely to do harm and that the automated …
=> Fix New Relic agent configuration

bin/run.sh
In the startup script, wrap the `newrelic-admin` call in an if/then clause to catch errors from it. The output from that call should still be logged.
Currently, a failure in recording the deployment with New Relic causes the run.sh script to crash, which prevents an application instance from starting.
I don't have a good mechanism in mind to test this other than deploying to staging and observing its behavior there. At this moment staging start-up is failing due to errors in the newrelic-admin call (ultimately due to egress proxy issues), so there's not much to lose in that environment.
We can view recent deploys via the cloud.gov dashboard so compromising the New Relic deployment information is low-risk in the short term.
=> Catch newrelic-admin errors in run script

bin/run.sh, manifest-production.yml, manifest-staging.yml, newrelic.ini
1. Add a new `NEW_RELIC_ADMIN_HOST` environment variable, set it to `api.newrelic.com` via the manifest files, and set it as the value of `NEW_RELIC_HOST` for the `newrelic-admin record-deploy` script call on startup. This works around a bug in the New Relic script command that makes it fail when the app's New Relic host is set to `gov-collector.newrelic.com`.
2. Update a deprecated setting name in `newrelic.ini`. The setting is disabled but this will keep the deprecation warning out of the New Relic log file in the application container.
3. Set the New Relic log level to `debug`. This should be set back to `info` once we've resolved our New Relic issue.
=> Troubleshoot New Relic configuration

.profile, bin/run.sh
Set the `NEW_RELIC_PROXY_HOST` environment variable to the egress proxy URL during app initialization.
Previously we set that only for the `newrelic-admin record-deploy` script command on startup, but the New Relic agent likely needs that configuration as well.
Compare to the notifications-api configuration, which is successfully running the New Relic Python agent against their FedRAMP-compliant collector through an egress proxy: https://github.com/GSA/notifications-api/blob/main/.profile#L8
Merge the change and deploy it to staging; I'll shake out that container manually once it's there.
=> Set NEW_RELIC_PROXY_HOST env var during app initialization

docs/deployment-process.md, docs/egress.md, newrelic.ini
Update the developer documentation for egress proxy setup and Tock deployment. This documents the egress proxy updates we've just applied in staging to restore New Relic traffic.
Also reduce the New Relic agent log level back to `info`.
Addresses #1792 .
Once deployed, SSH into the tock-staging container and confirm that the New Relic agent is only logging at the info level and above:
```bash
tail /tmp/newrelic-python-agent.log
```
With this update, we are clear to deploy the changes that have accumulated in staging over several weeks, including these latest changes for New Relic data.
That will consist of three steps:
1. Manually update and re-push the production egress proxy, following the [updated docs](https://github.com/18F/tock/compare/tock-1792-cleanup-and-docs?expand=1#diff-d4026c9 …
=> Update deployment docs and lower New Relic log level

docs/egress.md, egress_proxy/tock.vars.yml
Remove `google-analytics.com` from the egress proxy allow list. @cantsin and I haven't found any reason that we would be sending data there from Tock's server side, and I've applied that update in staging without issue.
This PR also tidies up some small omissions in the egress proxy deployment docs.
This follows up work for #1792.
After merge, I will apply the egress proxy config change in production following [these docs](https://github.com/18F/tock/blob/main/docs/egress.md#tock-staging-setup).
This PR doesn't include any changes in the deployed Tock application code, so there's no need for an immediate production release.
=> Remove google-analytics.com from the egress proxy allow list

Pipfile, Pipfile.lock, tock/hours/tests/test_integration.py
Adjust the project's dependency requirements in the Pipfile and install available updates.
`cg-django-uaa` needs to be at version 2.1.5 or greater to be compatible with Django 4.x, based on an installation requirement.
`cg-django-uaa` 2.1.5 is not compatible with Django below version 4.x, so this updates the `django` requirement accordingly. For good measure I've also constrained it to disallow updating Django to a new major version without deliberately updating the Pipfile.
Confirm that the automated tests pass. Once it's merged, I'll monitor the cloud.gov environment and confirm that the updated application starts correctly in that environment.
I've smoke-tested this update in a local development environment, including the admin console and API. I'll repeat that in staging, taking …
=> Apply all current Python package updates

api-docs/timecards.md
Update the documentation for the `/timecards.json` endpoint.
* Add notes about zero values for hours and allocation
* Update the fields included in the response
This follows up #1820.
=> Update API docs for timecards endpoint
