18F/tock

.travis.yml
tock/hours/tests/test_models.py
tock/projects/tests.py

fixed travis

---

tock/hours/forms.py
tock/hours/tests/test_forms.py
tock/tock/static/css/style.css

fixes to forms and test coverage

---

tock/hours/forms.py
tock/tock/templates/hours/timecard_form.html

@seanherron This, for some crazy reason, works.

Fixed the formset problem

---

README.md

When I was working on changing some styles, I noticed that there were no specific instructions or guide on how to do this. This pull request includes adding those instructions to the `README.md` file so that future contributors have a better understanding on how to submit those types of changes.

Adding more instructions to README to include how to compile and submit style changes.

---

tock/hours/migrations/0005_auto_20150413_1839.py
tock/hours/models.py
tock/tock/templates/hours/timecard_form.html

Allow decimal points in time reported

---

README.md

swap tick (') for backtick (`) (smart quotes?)

---

tock/projects/models.py

testing functionality of help_text per #166

adding helptext

---

.travis.yml
requirements-dev.txt
tock/.coveragerc
tock/tock/settings/test.py

To figure out how we're doing on test coverage.
[Resolves #190]

Add coverage and codecov integration.

---

tock/employees/views.py
tock/hours/tests/test_views.py
tock/hours/urls/timesheets.py
tock/hours/views.py
tock/tock/utils.py

* Add a `PermissionMixin` to make Django generic views compatible with DRF-style permission classes
* Add `IsSuperUserOrSelf` permission class
* Apply said permission instead of overriding `dispatch`
* Update tests
* Delete unused code

Use DRF-compatible permission classes for auth logic.

---

tock/hours/admin.py
tock/hours/forms.py
tock/hours/models.py
tock/hours/templatetags/has_submitted_timesheet.py
tock/hours/tests/test_forms.py
tock/hours/tests/test_integration.py
tock/hours/tests/test_models.py
tock/hours/tests/test_templatetags.py
tock/hours/tests/test_views.py
tock/hours/utils.py
tock/hours/views.py

- Make sure test cover enough code to refactor without unexpected issues. 
- Ensure PEP8 
- General simplification of code and adding doc strings.  
[Resolves #193]

hours app cleanup and test coverage

---

tock/api/tests.py
tock/api/views.py

Added tests to cover most of the API view custom methods.

API tests and some documentation updates

---

tock/tock/templates/projects/project_list.html

remove billability indicator from project_list.html

nix-billability-ind

---

tock/tock/templates/hours/timecard_form.html
tock/tock/templates/projects/project_list.html

remove the "billable" dollar icon from the timecard form cc @ramirezg. left some extra html in there to preserve existing formatting.  can probably be removed.

bill-ico-nix

---

tock/api/tests.py
tock/api/views.py

adding the flat rate indicator to the timecard and bulktimecard api views
cc @ramirezg @shawnbot

api-flat-rate

---

Hiring as a Service - USDS
Military OneSource Agile Acquisition
OCSIT/Developer Program
OGP Payroll Reporting Project

Cleaning up some project-specific debris from the repo...

Just a little hygiene

---

tock/employees/forms.py
tock/employees/migrations/0006_userdata_current_employee.py
tock/employees/models.py
tock/employees/tests/test_forms.py
tock/employees/tests/test_models.py
tock/employees/tests/test_views.py
tock/employees/views.py
tock/hours/tests/test_views.py
tock/hours/views.py
tock/tock/templates/hours/reporting_period_detail.html

Added a new field the UserData model which indicates if a user is currently employed. 
Filtered the reporting period reports to only show users marked as currently employed. 
This should make it significantly easier to determine which employees need to fill out their time cards and the first step in creating an automated system for getting users to fill out their time cards.

Current employee

---

tock/api/tests.py
tock/api/urls.py
tock/api/views.py

Adding endpoint that lists users who have not completed their timecards for as given period.
The bot for consuming this api is [here](https://github.com/geramirez/tock-bot)

Reporting Period Audit

---

tock/tock/templates/hours/timecard_form.html

updating weekly admin message and linking to projects page

Change admin message

---

tock/employees/forms.py

updating help text in the ui to make tock more friendly to our friends in ocsit (some which are going to start using tock)

make a tiny content change to the ui

---

tock/hours/migrations/0012_auto_20151224_1625.py

migrations fix

---

tock/tock/templates/hours/timecard_form.html

update timecard message for new year's day / ooo

update timcard message for new year

---

tock/projects/tests.py
tock/projects/views.py

This PR addresses [issue #289](https://github.com/18F/tock/issues/289), the micro-purchase auction to "Fix data visualization in Tock user interface". 
This code limits the number of time periods displayed in the table in the project detail page (/projects/:id) to the five most recent time periods by filtering the data in the `project_timeline` method in `project/views.py`. 
New unit tests for this functionality can be found in `projects/tests.py`.
All new code is [PEP 8](https://www.python.org/dev/peps/pep-0008/) compliant.

Limit to 5 recent periods in table on project detail page

---

README.md

Just writing down what Shawn told me.  This is a helpful note so I don't forget
and save future me (or a new person) from needing to dig through the code 
or ask @shawnbot

Very brief API docs

---

tock/projects/models.py

projects will now be listed in alphabetical order globally

set ordering or projects to alpha

---

tock/tock/templates/hours/timecard_form.html

new message + got rid of some old commits

cleaning up broken build + update

---

requirements.txt

re: #264 and #286 updating to django 1.8.9 cc @monfresh @cmc333333
tested locally, passes all tests.

update django ver

---

tock/tock/templates/hours/timecard_form.html

Added an out of office reminder

---

tock/tock/templates/hours/timecard_form.html

@batemapf Please remove the OOO message

removed the OOO message

---

tock/tock/templates/hours/timecard_form.html

edit timecard message re new features

---

tock/employees/admin.py
tock/employees/migrations/0002_auto_20150429_1851.py
tock/employees/migrations/0003_auto_20150430_1815.py
tock/employees/migrations/0004_employee.py
tock/employees/migrations/0005_delete_employee.py
tock/employees/migrations/0006_userdata_current_employee.py
tock/employees/models.py
tock/employees/tests/test_models.py
tock/hours/migrations/0001_initial.py
tock/hours/migrations/0002_auto_20150405_0317.py
tock/hours/migrations/0003_auto_20150408_1934.py
tock/hours/migrations/0004_auto_20150408_1934.py
tock/hours/migrations/0005_auto_20150413_1839.py
tock/hours/migrations/0006_auto_20150428_0150.py
tock/hours/migrations/0007_reportingperiod_message.py
tock/hours/migrations/0008_auto_20150514_1651.py
tock/hours/migrations/0009_remove_timecardobject_time_percentage.py
tock/hours/migrations/0010_auto_20150519_1436.py
tock/hours/migrations/0011_auto_20151203_1532.py
tock/hours/migrations/0012_auto_20151224_1625.py
tock/hours/migrations/0013_timecardobject_notes.py
tock/hours/migrations/0014_timecard_submitted.py
tock/projects/migrations/0001_initial.py
tock/projects/migrations/0002_auto_20151020_2043.py
tock/projects/migrations/0003_auto_20151103_2041.py
tock/projects/migrations/0004_remove_project_priority.py
tock/projects/migrations/0005_project_mbnumber.py
tock/projects/migrations/0006_auto_20151229_1618.py
tock/projects/migrations/0007_auto_20160310_0136.py

Reverts 18F/tock#348
The migration squashing of the hours related models created some strange side-effects -- reverting until we figure it out

Revert "Add org to employee model"

---

requirements-dev.txt
tock/hours/forms.py
tock/hours/views.py
tock/projects/views.py
tock/tock/templates/projects/project_list.html

Update nplusone and add eager loads.

---

tock/api/views.py

to ensure a little CLI mini-app (low tech Angry Tock, while that is offline) i concocted captures _all_ of the tock truants!!

increase page size for reporting period audits

---

tock/hours/views.py

This fix addresses an issue with alerts not appearing due to other new features going in at the same time.
/cc @batemapf

Quick alerts fix

---

tock/projects/migrations/0012_auto_20160705_2231.py
tock/projects/models.py

see #358. orders by agency, then office.

fix acct code ordering

---

runtime.txt

- deployed to `tock-staging`, no issues
- passes all tests

upgrade to python 3.5.2 from 3.4.3

---

tock/tock/templates/hours/reports_list.html

Related to #384 
cc @zacharycohn

adding a bulk download link

---

.travis.yml
Dockerfile
docker-compose.yml
requirements-dev.txt
requirements.txt
tock/api/renderers.py
tock/api/urls.py
tock/api/views.py
tock/hours/views.py
tock/projects/urls.py
tock/projects/views.py
tock/tock/settings/base.py
tock/tock/settings/dev.py
tock/tock/settings/production.py
tock/tock/urls.py

Fixes #416
This changeset updates all of Tock's project dependencies to their latest versions.  This includes the following changes:
* Updates the `requirements.txt` and `requirements-dev.txt` files to account for all package updates
* Fixes line endings in `requirements-dev.txt`
* Updates the `Dockerfile` and `docker-compose.yml` setup to include the latest stable versions of Python, PostgreSQL, and nginx
* Addresses several deprecation warnings that appeared in the tests due to the updated packages
* Updates and fixes the Travis config
While fixing the remaining Django issues (and I was wrong, `1.10.1` is the latest version!), I noticed that Python 3.4 was still being used by the Docker container so I went through and ended up taking care of all of the remaining project dependencies
A …

Update all Tock project dependencies

---

Procfile
manifest.yml
tock/employees/tests/test_views.py
tock/hours/tests/test_integration.py
tock/hours/tests/test_views.py
tock/tock/remote_user_auth.py
tock/tock/tests/test_remote_user_auth.py

Code tweaks for new auth and hosting arrangement

---

tock/api/views.py

@adelevie's delight. adding the `active` attribute to the project serializer.

add active field to projects endpoint

---

staging-manifest.yml
tock/api/tests.py
tock/employees/models.py
tock/employees/tests/test_models.py
tock/tock/settings/base.py

Add API Authentication

---

tock/employees/admin.py

add search box to employees admin page

add-search-field

---

tock/tock/templates/employees/user_form.html

Updating template to comply with changes to where CSV's live via #477.

Fix missing chart data

---

tock/tock/templates/employees/user_detail.html

I bet this is why people say you shouldn't copy and paste code...

Patching #492

---

package.json
tock/tock/templates/base.html

Also, this builds CSS before watching, which solves the problem of CSS not loading on the first time the Docker image builds (without having to change the SCSS to trigger a build).

Remove IE8 shims and fix indentation

---

requirements.txt

Thinking this is what caused fails on #506 and #505...

move to 10.1.2

---

tock/employees/forms.py

Remove Legacy OCSIT mention and make option more generalizable (e.g. to
include 18F Acquisitions, PIFs, OPP, etc…)

Update for TTS

---

tock/tock/templates/hours/timecard_form.html

Updates day to tock from Monday to Friday on timesheet alert message, to align with our new tocking deadlines.
Resolves #524.
cc: @joshuabailes

Update day to tock on timesheet alert message

---

requirements.txt

Upgrades us to the latest version of Django to address a security issue.
Here's the announcement fro, Django regarding the update: https://groups.google.com/forum/#!msg/django-announce/UgSbuZK4NdI/4ISgsD62CAAJ

Update to Django 1.10.3

---

tock/hours/tests/test_views.py
tock/hours/urls/reports.py
tock/hours/views.py
tock/tock/templates/hours/reports_list.html

Addresses #471, which was listed as @joshuabailes top priority. This change creates a new CSV report that is limited to all General entries that have snippets (notes is the Tock terminology). The report is accessible in the Reports section under "Regular Reports".
Example of CSV output:

Snippets report

---

tock/tock/templates/utilization/group_utilization.html
tock/utilization/tests/test_views.py
tock/utilization/views.py

Adds a summary row to the utilization report page for each unit.
Screen shot of changes:
---

Util summary row

---

tock/tock/templates/hours/reporting_period_user_detail.html
tock/tock/templates/utilization/group_utilization.html

Content Tweaks

---

tock/tock/templates/hours/reports_list.html

Aligns the "FY2017" link on the reports list page to actually align with FY2017.
cc @MKathrynC

Fix FY2017 report

---

tock/tock/templates/base.html

Resolves https://github.com/18F/tock/issues/591 by adding the Google Analytics code for the `Internal Systems` property.  Holler with any questions in #g-analytics in slack.  
https://github.com/18F/analytics-standards#18f-snippet-standards-for-website-analytics

adding google analytics

---

tock/tock/templates/hours/dashboard.html

Word changes to dashboard page.

quick content tweaks to dashboard page

---

requirements-dev.txt

Due to a package rename, we need to update factory-boy to the latest version.

updating factory-boy to resolve a dependency error.

---

about.yml

Adds an about.yml, per https://github.com/18F/Infrastructure/issues/685
This is a non-user-facing change.

minimum viable about.yml.

---

deploy.sh
manifest.yml
newrelic.ini
requirements.txt
tock/tock/newrelic.py
tock/tock/wsgi.py

Adding configurations for newrelic so we can get monitoring going, per the ATO checklist.

newrelic configuration

---

tock/tock/wsgi.py

Still working on getting newrelic running. Not being able to test it locally means allll the PRs.

Fixing an import error

---

tock/tock/wsgi.py

Getting newrelic set up to monitor tock.

import problems fixed for real this time

---

tock/tock/templates/projects/project_detail.html

This adds a CSV for a project's bulk data on the project page. It's in the same format as the overall bulk data download, but only includes the data for that project.

Project bulk data

---

Procfile
init.sh
manifest.yml
requirements.txt

This should close #671 when it's merged into Master. Pairing with @ccostino and we managed to get it deployed to staging and it worked.

Update to gunicorn/gevent

---

README.md
docker-compose.yml

Pairing with @ccostino on this. We now have `pdb` support with local Tock development.

Adding Python Debugger

---

tock/tock/remote_user_auth.py
tock/tock/tests/test_remote_user_auth.py

**Note that this is a PR against #720, not the master branch.**
This fixes `remote_user_auth.py` and its tests.

Fix remote_user_auth.py and its tests.

---

tock/tock/templates/_navigation.html
tock/tock/templates/logout.html
tock/tock/tests/test_url_auth.py
tock/tock/tests/test_views.py
tock/tock/urls.py
tock/tock/views.py

Add logout view and menu item

---

.circleci/config.yml

Set the git tag in the environment

---

.circleci/config.yml
tock/tock/context_processors.py
tock/tock/settings/base.py
tock/tock/urls.py
tock/tock/views.py

This fixes both the CircleCI deployment of Production and adds better
context to what version is on both Staging and Production whenever it
gets deployed.
cc: @toolness

Modify footer link context processor

---

.circleci/config.yml

Target the API before attempting Auth

---

.circleci/config.yml

:grumble: :grumble: read the docs :pensive:

Just use login

---

tock/tock/static/sass/core.scss
tock/tock/templates/base.html
tock/tock/templates/hours/reporting_period_list.html

the current footer text sits awkwardly on the left margin; this should(?) fix that?
What it looks like now:

adding a footer

---

.circleci/config.yml
.gitignore
tock/tock/context_processors.py
tock/tock/settings/base.py

Read version information from a file

---

tock/tock/context_processors.py
tock/tock/settings/base.py
tock/tock/templates/_navigation.html
tock/tock/templates/base.html

Add multiple links to Tock Change Request Form

---

manifest-production.yml

This is good to be reviewed and merged, but let's not cut a release for this just yet as we're in the midst of a code-freeze for the ATO assessment.

Rename credentials service in production

---

docs/local-development.md

A few more capitalization + stylistic updates :thumbsup:

Capitalization + stylistic updates (local dev)

---

docs/deployment-process.md

Capitalization + light stylistic updates to this section. Note: For capitalization of technical terminology (e.g., GitHub releases), I looked online to see what the most common capitalization conventions were. (Feel free to reject any capitalization suggestions, though.)

Capitalization + stylistic updates

---

api-docs/users.md

Standard capitalization updates (plus one tiny change to the first sentence).

Capitalization updates

---

api-docs/timecards.md

Standard capitalization changes + small change to text in the `Optional` section.

Capitalization + style changes

---

docs/logging.md

One updated sentence in the contextual intro copy and a few capitalization changes (for standardization purposes).

More capitalization + stylistic changes!

---

api-docs/projects.md

Basic capitalization updates, plus a few small changes to the intro sentence + copy in the `Notes` section.

Copy + capitalization updates

---

api-docs/reporting-period-audit-specific.md

Standard capitalization changes + an update to the page title (which duplicated another page's title).

Capitalization + title change

---

.circleci/config.yml
README.md

Update badges to Snyk and remove Gemnasium

---

docs/README.md
docs/backup-and-restore-database.md
docs/logging.md

This patch adds logging documentation covering Admin Recent Activity and
documentation around backing up and restoring the database manually.

Add documentation around logging and backups

---

tock/hours/views.py
tock/tock/templates/hours/reporting_period_list.html
tock/tock/templates/hours/timecard_form.html

Address #804 
This changeset is an attempt to improve the user experience a bit around the buttons and info/error messages when saving or submitting the form.  Specifically, it addresses the following:
* Swaps the order of the save and submit buttons
* Makes the submit button noticeably larger
* Changes the style of the save button to be a secondary button
* Shifts form info and error messages to appear at the top and bottom of the timecard for improved visibility
* Provides alert titles to the messages displayed
* Fixes the display of most alerts
* Adds a submission success mesage
This is just a start; more improvements can certainly be made!

Improve timecard form UX

---

tock/tock/middleware.py
tock/tock/settings/base.py
tock/tock/settings/dev.py
tock/tock/settings/test.py
tock/tock/tests/test_middleware.py

This PR closes and address #812
Right now the timeout is for 60 minutes. But for testing purposes I've set it to 3 seconds by overriding it in the test specifically. I tested this locally too with a setting of 1 minute and it worked beautifully. ![swedishchef-myspace](https://user-images.githubusercontent.com/706004/41481907-bfbbecb4-70a1-11e8-865a-33846d868361.jpg)

Add Auto Logout functionality

---

tock/tock/settings/base.py
tock/tock/wsgi.py

Pulling whitenoise fix into master to fix staging

WhiteNoise configuration needs to be in middleware and not in wsgi

---

Pipfile.lock
package-lock.json
tock/tock/context_processors.py
tock/tock/settings/base.py
tock/tock/settings/dev.py
tock/tock/utils.py
tock/tock/wsgi.py

Following [instructions](https://github.com/18F/tock/blob/master/docs/local-development.md) to bring up local development environment is currently broken.
Issues I faced when following the instructions:
I am fixing it by removing all the `auth.permission` entries in `tock/test_data/data-update-deduped.json`, since they conflict with what was already in the database.
I am fixing that by what was suggested from the [upgrade instructions here](http://whitenoise.evans.io/en/stable/changelog.html#v4-0)
This is fixed by regenerating the Pipenv.lock file because the older version has two versions of Django installed which they conflict with each other.   (Thanks @Jkrzy for discovering that)

Fixing Local Development Environment

---

docs/google-script-integration.md
docs/onboarding.md

Correcting, clarifying, and adding a step  to the onboarding docs resulting from working through the process with @tbaxter-18f

Update Google script names and onboarding docs

---

package-lock.json

Updating javascript dependencies via `npm update` for #891

Update javascript dependencies

---

docs/logging.md

The tock log audit process needs some better documentation.  This PR is a first stab at creating that documentation.

Document tock log audit process

---

tock/tock/settings/base.py

Our ISSO has requested that we make sure our app comply with https://cyber.dhs.gov/bod/18-01/, so I turned on more HSTS headers.

added HSTS headers

---

Pipfile.lock
requirements.txt

Updating Django and a few other dependencies

Update python dependencies

---

tock/employees/models.py

Our business units are way out of date.

update business units

---

package-lock.json
tock/projects/admin.py
tock/projects/models.py

Resolves #969 to show the ID as well as name of projects. Plus some mild cleanup

Show project ID with name

---

package-lock.json
package.json

Updating development javascript dependencies

Update js dev dependencies

---

package-lock.json

Another quick javascript dependency update ahead of the next release.

Update javascript development dependencies

---

docs/dependency-management.md

Updated dependency management docs to cover update approaches both from a local environment and using docker.

Update python dependency management docs

---

docs/utilization.md

The example for week 2 referred to week 1.
Include a high-level description of the issue your pull request fixes; include only one issue per pull request. Link to the GitHub issue it resolves.
* Notes

Utilization doc update

---

.circleci/config.yml
README.md
api-docs/project-info.md
api-docs/reporting-period-audit-specific.md
docs/deployment-process.md
docs/logging.md
docs/onboarding.md
tock/tock/context_processors.py
tock/tock/settings/base.py
tock/tock/templates/utilization/group_utilization.html

Updating references to default git branch `main`.
Includes circleci config updates.

Update references to default git branch

---

tock/tock/templates/_sidebar.html

This attempts to resolve #1139 by adding the missing link locations. These are my best guesses for what the intended target of each link was supposed to be. If @hbillings has better ideas for where they should point, I'm happy to change them.

Fix missing links in sidebar

---

Pipfile
Pipfile.lock
tock/tock/static/js/components/save_csv.js
tock/tock/templates/utilization/utilization_analytics.html
tock/utilization/analytics.py
tock/utilization/templatetags/analytics.py
tock/utilization/views.py

This builds on the new utilization graph with a textual data table, improved hover labels, and CSV download of the raw data table.
There is an added Python dependency on `pandas` which is very, very useful for handling data and graphics. We use a custom template tag to render the data frame into the HTML table and pass the data frame as an argument to make the plot.

Include raw data table and tweak graph

---

tock/tock/templates/uaa_client/login_error.html

Creates a more user-friendly error message for authentication issues.
resolves #1147

Improve authentication error message

---

.circleci/config.yml

Continuation of **https://github.com/18F/tock/pull/1150** with a few corrections to environment variable references in our circleci config to get us back to working staging deploys

Correct env variable references in circleci config

---

package-lock.json
tock/tock/static/sass/_header.scss

Fix subnav mobile expansion issue. Close #1154 
* Notes

fix css mobile subnav issue fix #1154

---

tock/employees/views.py

Alphabetize the employees by last name, first name on `/employees` page
resolves #1032

Alphabetize the employee listing

---

docs/README.md
docs/incident-response.md

Add incident response plan to docs

---

docs/diagrams/ci-cd.puml

Bringing into diagrams branch, thanks @timoballard!

ci-cd-network diagram

---

Pipfile
Pipfile.lock
package-lock.json
package.json

Catching the latest dependency versions for python and javascript

Dependency updates

---

tock/tock/static/js/components/timecard.js
tock/tock/tests/js/integration/timecard.test.js

Fixes [immediate JS problem with delete](https://gsa-tts.slack.com/archives/C1JFYCX3P/p1614376281000900), but there seems to be an ordering issue where the assumption is that the deleted line is the bottom-most one.

fix JS error but there is a deletion ordering problem

---

.circleci/config.yml
Dockerfile
Pipfile
Pipfile.lock
runtime.txt

Moving to latest version of python supported by cloud.gov buildpack.

Update python to 3.8.5

---

Pipfile.lock
requirements.txt
tock/tock/templates/base.html
tock/tock/templates/projects/project_detail.html

Updates Django to 3.1.17 as well as update some codes
`staticfiles` is depreciated, replaced with `static`. 
Resolves #1310

Redid the branch with files updated from the latest release. 

---

Pipfile.lock
requirements.txt

run sync and update req.txt

---

tock/tock/settings/base.py

this will support the operation to append items to the middleware
list in `settings/prod.py` including the csp.
Include a high-level description of the issue your pull request fixes; include only one issue per pull request. Link to the GitHub issue it resolves.
* Notes

switch middleware to list

---

tock/tock/settings/production.py

remove the local static directory from the `csp` since would be the same as `self`
* Notes

remove static from csp because no cdn or s3

---

manifest-production.yml

increase memory usage and reduce instances to  deploy data migration

increase memory usage and reduce instances to  deploy

---

manifest-production.yml

Change production memory to 1024M and instance count to 4

Change production memory and instance count

---

tock/maintenance_page/index.html

Fixes invalid HTML, adds a `lang="en-US"` attribute to the `html` element, adds a heading element, and adds a `main` element to wrap the contents. There are no more errors or warnings in WAVE.
Closes #1535

Update maintenance page for accessibility

---

tock/tock/tests/js/integration/timecard.test.js

Added test that the value was reset to blank after weekly billing was selected

Added test that the value was reset to blank after weekly billing 

---

docs/compliance.md

Every month, we are required to deactivate Tock users who have left the organization. Adding some documentation and a provided script towards this process.

document how we deactivate users

---

.profile

We also need to set http_proxy; currently, hitting http://google.com works but not https:// so let's fix that oversight.

add http_proxy env

---

tock/tock/templates/utilization/utilization_analytics.html
tock/utilization/templatetags/analytics.py
tock/utilization/views.py

For ticket: #1566 
Copied and updated the `frame_table` tag as `df_table` to use a custom table instead of the pandas dataframe.to_html output.
This PR does not address the `Headcount` table issues. The headcount table needs to be reviewed by design to devise a better solution for this information.

Fix empty header cells in utilization table

---

docs/compliance.md
scripts/.gitignore
scripts/compliance.py

Added compliance.py to complete #1648. The documentation was updated.

Added compliance.py to complete issue #1648. Updated documentation.

---

Pipfile.lock
requirements.txt

PR to replace #1655 
Pipfile and requirements.txt are slightly out of sync.
* Updated Pipfile
* pipenv requirements | sort > requirements.txt

Syncing up dependency updates

---

requirements.txt

Syncing up dependency updates - fic

---

Pipfile
Pipfile.lock

To fix an issue detected by Snyk related to a transitive dependency setuptools@39.0.1.

Workaround to override zope sub dependency setuptools@39.0.1

---

manifest-production.yml

I forgot to also fix production for NR deployment errors. Fixed in this PR.

new relic certificate fix for production

---

Pipfile.lock

Pipfile.lock recreated to fix issue on CircleCi.

Recreate piplock

---

docs/egress.md

egress documentation

---

docs/egress.md

Reworks the existing documentation to include steps that I found helpful along the way. Caution: since the egress server is not behaving as expected, it's quite possible some of these steps are wrong!

updates egress documentation

---

docs/egress.md
egress_proxy/manifest.yml
egress_proxy/tock.vars.yml

Adding egress configuration files for easier reference/deployment.

add egress_proxy configuration files

---

docs/egress.md

egress documentation: specify tcp port

---

tock/tock/settings/base.py

Addresses https://github.com/18F/tock/issues/1763

weekly billing: add 75% as an option

---

docs/diagrams/ci-cd.puml
docs/diagrams/data_flow.puml

This PR fix the diagrams. The fix is a change to the url for the preview.
- data_flow.pml
- ci-cd.puml

Small fix to diagrams

---

tock/api/views.py
tock/hours/tests/test_views.py

Minor API change to not echo user input

API: do not echo user input
